### PR TITLE
Use µ as default abbreviation for micro.

### PR DESCRIPTION
**Pull request by ericpre**
As suggested and discussed in #666, this PR sets `µ` as default abbreviation for micro.

### CODE REVIEW

**Comment by hgrecco** [comment]
Thanks for the PR. I have a more general questions. Should we provide a Unicode and non Unicode version of symbols, abbreviation and unit names?

**Comment by jondoesntgit** [comment]
Something akin to sensing whether babel is installed?

Would this mean we would have two default.txt files, one with Unicode and the other without?

**Comment by cpitclaudel** [comment]
Merging this would be great, though a more general way to change a unit's default abbreviation would be great.

**Comment by hgrecco** [comment]
I am still doubtfull about unicode support. How to distinguish/select?

**Comment by ericpre** [comment]
There are only a few symbols or abbreviations with the unicode issue in python 2.7, one way to deal with it is simply to [ignore these when reading definitions](https://github.com/hgrecco/pint/pull/680/files#diff-d36b35485d40005c8f0bf6dcfd421a39R48).

This fixes the following on python 2.7:
```python
import pint
ureg = pint.UnitRegistry()
a = 1.0E-6*ureg.hbar
print("{:~P}".format(a))
```
which is raising an `UnicodeEncodeError` on master since it can't read the alias (`ħ`); same for `Ω` (ohm), `σ` (Stefan Boltzmann constant), `Å` (ångström).
There is also an `UnicodeEncodeError` with `P/` (printers_pica) on python 2.7 and I don't know what is this abbreviation, so I would prefer not to touch it.

The tests on python 2.7 are failing because the expected `UnicodeEncodeError` is not raised! :( Locally, the error is nicely raised...

**Comment by ericpre** [comment]
@hgrecco, do you think the fix of this PR to deal with unicode character on python 2.7 is sensible? If so I will work out the test failure.

**Comment by hgrecco** [comment]
Sorry for the delay. It looks good to me. Go ahead

**Comment by ericpre** [comment]
Thanks @hgrecco for the feedback! The test failures are fixed now.

**Comment by hgrecco** [comment]
thanks

**Pull request merged**
