### PR TITLE
improve the application registry

### LINKED ISSUE #1365: improve the application registry for use in packages
xref xarray-contrib/pint-xarray#129

The currently recommended way to use the application registry is:
```python
# application
ureg = pint.UnitRegistry()
# configuration
pint.set_application_registry(ureg)

import package_using_pint

# package_using_pint
registry = pint.get_application_registry()
```

There are a few issues with this:
1. there's code before an import so tools like `isort` will complain
2. since all `set_application_registry` does is assigning its argument to a module-global, all other references to the previous object are not updated.
3. as a consequence of 2, packages providing new registries either need to be imported before packages using them, or they need to provide a setup function that needs to be called before the import of those packages

I don't really like setup functions, though, especially if the package can clearly separate the unit registry from other functionality. E.g. `import cf_xarray` does not even try to import `pint`, but `import cf_xarray.units` will create and set a custom unit registry.

To solve this, I'd like to propose exposing a `UnitRegistry` wrapper object as `pint.application_registry`:
```python
class ApplicationRegistry:
    def __init__(self, registry):
        self._registry = registry

    def set(self, new):
        self._registry = new

    def __getattr__(self, name):
        return getattr(self._registry, name)

    def __dir__(self):
        return dir(self._registry)

    # other __*__ methods

application_registry = ApplicationRegistry(_DEFAULT_REGISTRY)
```
with this, packages using the application registry can just `import pint` or `from pint import application_registry`, and other packages providing a registry can call `.set` to have all other packages get the new registry, without having to care when/in which order they are imported.

Also note that this is completely independent of the `get/set_application_registry` functions.

Not sure if I'm missing something obvious, but if this sounds like a good idea I'll send in a PR.

### PR DESCRIPTION
**Pull request by keewis**
This adds the application registry wrapper object proposed in #1365 to make the application registry easier to use between packages. `get_application_registry` and `set_application_registry` were changed to use the new wrapper class.

No docstrings, docs or extra tests, yet, and the testsuite still fails.

cc @jthielen

- [x] Closes #1365, closes xarray-contrib/pint-xarray#129
- [x] Executed ``pre-commit run --all-files`` with no errors
- [x] The change is fully covered by automated unit tests
- [ ] Documented in docs/ as appropriate
- [ ] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by keewis** [comment]
This still needs to be documented, but the code should be ready for review.

**Comment by kthyng** [comment]
Looking forward to this to simplify my files! Thanks for your work!

**Comment by hgrecco** [comment]
I agree with the implementation. I think we need to document this very clearly as has raised multiple questions in the past. Great work!

**Comment by keewis** [comment]
@hgrecco, @jules-ch, would it be fine to merge this without the docs and I'll add documentation in a new PR?

**Comment by hgrecco** [comment]
I agree

**Comment by jules-ch** [comment]
Sorry I haven't had time to review PRs pr issues lately. I'm okay to merge this, @keewis  can you create a PR for documentation for this feature. I think we will do this with the rework on documentation.

**Comment by jules-ch** [comment]
Merging this :+1:

**Pull request merged**
