### PR TITLE
Sphinx and readthedocs fixes

### LINKED ISSUE #881: Sphinx errors
Downstream of #880, I'm still getting a few errors when running sphinx-build:

```
pint/docs/plotting.rst:32: WARNING: Exception occurred in plotting plotting-1
 from pint/docs/plotting.rst:
Traceback (most recent call last):
  File "pint/pint/quantity.py", line 1476, in __getitem__
    value = self._magnitude[key]
TypeError: 'int' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/matplotlib/sphinxext/plot_directive.py", line 499, in run_code
    exec(code, ns)
  File "<string>", line 13, in <module>
  File "site-packages/matplotlib/axes/_axes.py", line 798, in axhline
    yy = self.convert_yunits(y)
  File "site-packages/matplotlib/artist.py", line 195, in convert_yunits
    return ax.yaxis.convert_units(y)
  File "site-packages/matplotlib/axis.py", line 1521, in convert_units
    if munits.ConversionInterface.is_numlike(x):
  File "site-packages/matplotlib/units.py", line 126, in is_numlike
    for thisx in x:
  File "pint/pint/quantity.py", line 1480, in __getitem__
    "supports indexing".format(self._magnitude))
TypeError: Neither Quantity object nor its magnitude (26400)supports indexing
pint/docs/plotting.rst:52: WARNING: Exception occurred in plotting plotting-2
 from pint/docs/plotting.rst:
Traceback (most recent call last):
  File "pint/pint/quantity.py", line 1476, in __getitem__
    value = self._magnitude[key]
TypeError: 'int' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/matplotlib/sphinxext/plot_directive.py", line 499, in run_code
    exec(code, ns)
  File "<string>", line 16, in <module>
  File "site-packages/matplotlib/axes/_axes.py", line 798, in axhline
    yy = self.convert_yunits(y)
  File "site-packages/matplotlib/artist.py", line 195, in convert_yunits
    return ax.yaxis.convert_units(y)
  File "site-packages/matplotlib/axis.py", line 1521, in convert_units
    if munits.ConversionInterface.is_numlike(x):
  File "site-packages/matplotlib/units.py", line 126, in is_numlike
    for thisx in x:
  File "pint/pint/quantity.py", line 1480, in __getitem__
    "supports indexing".format(self._magnitude))
TypeError: Neither Quantity object nor its magnitude (26400)supports indexing

pint/pint/quantity.py:docstring of pint.Quantity:: WARNING: py:class reference target not found: any numeric type                                                                                                                   
pint/pint/quantity.py:docstring of pint.Quantity.from_list:: WARNING: py:class reference target not found: list of pint.Quantity
pint/pint/quantity.py:docstring of pint.Quantity.from_sequence:: WARNING: py:class reference target not found: sequence of pint.Quantity
pint/pint/quantity.py:docstring of pint.quantity.Quantity:: WARNING: py:class reference target not found: any numeric type
pint/pint/quantity.py:docstring of pint.quantity.Quantity.from_list:: WARNING: py:class reference target not found: list of pint.Quantity
pint/pint/quantity.py:docstring of pint.quantity.Quantity.from_sequence:: WARNING: py:class reference target not found: sequence of pint.Quantity
pint/pint/systems.py:docstring of pint.systems.Group.from_lines:: WARNING: py:class reference target not found: str -> None

### PR DESCRIPTION
**Pull request by crusaderky**
- [x] Closes #881
- [x] Executed ``black -t py36 . && isort -rc . && flake8`` with no errors
- [x] The change is fully covered by automated unit tests
- [ ] ~~Documented in docs/ as appropriate~~
- [x] Added an entry to the CHANGES file

- Added travis tests to verify that sphinx can run. Note that most sphinx warnings will result in a green light anyway.
- Fixed a wealth of Sphinx errors and warnings. I could not fix all - notably there's a bunch of ``class reference target not found`` errors that I don't think are fixable with napoleon unless we moved to Python 3 typing annotations - which is a worthy thing to do, but which would also require much, much longer to implement than this PR.
- fixed readthedocs CI

### CODE REVIEW

**Comment by crusaderky** [comment]
RTD CI tested: 
- https://crusaderky-pint.readthedocs.io/en/sphinx/
- https://readthedocs.org/projects/crusaderky-pint/builds/10210620/
- ``python -m sphinx.ext.intersphinx https://crusaderky-pint.readthedocs.io/en/sphinx/objects.inv``

Travis tests inspected.

**Comment by crusaderky** [comment]
@hgrecco ready for review and merge. Note how my RTD tests were done on a brand new, vanilla environment - if you have manual settings in yours, they may or may not override readthedocs.yml.

**Comment by hgrecco** [comment]
Looks great to me! I will merge it and then we can check if everything is fine looking at the `latest` branch in rtd

**Pull request merged**
