### PR TITLE
Reinstate support for pickle protocol 0 and 1

### LINKED ISSUE #1036: __slots__ without __getstate__
Hi, I'm trying to pickle a df with hdf5. 

That fails with the below error because `__getstate__` has vanished from class `UnitsContainer`

```python
  File "/Users/csxds/workspaces/venvs/dimpact_test/lib/python3.7/site-packages/tables/attributeset.py", line 494, in __setattr__
    self._g__setattr(name, value)
  File "/Users/csxds/workspaces/venvs/dimpact_test/lib/python3.7/site-packages/tables/attributeset.py", line 436, in _g__setattr
    self._g_setattr(self._v_node, name, stvalue)
  File "tables/hdf5extension.pyx", line 708, in tables.hdf5extension.AttributeSet._g_setattr
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copyreg.py", line 73, in _reduce_ex
    "defining __getstate__ cannot be pickled") from None
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled
```
Any chance this can be brought back?

Many thanks

### PR DESCRIPTION
**Pull request by crusaderky**
- [x] Closes #1036 
- [x] Executed ``black -t py36 . && isort -rc . && flake8`` with no errors
- [x] The change is fully covered by automated unit tests
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by crusaderky** [comment]
@dschien @hgrecco ready for review and merge

**Comment by hgrecco** [comment]
Looks good to me. @dschien: Can you test it in your application?

**Comment by dschien** [comment]
> Looks good to me. @dschien: Can you test it in your application?

Dear @crusaderky @hgrecco 
thanks a lot for the quick response. I tested it locally and it works.
This is resolved for me.

**Pull request merged**
