### PR TITLE
Add Fake Units

### PR DESCRIPTION
**Pull request by Modelmat**
Add support for more units, not much point except for theoretics

based off http://www.mindspring.com/~jimvb/unitsystem.htm

### CODE REVIEW

**Comment by onealj** [comment]
First time I've seen those units. I would certainly be surprised and confused with unknown and non-standard prefixes that we thought up by some random website, not universally used or taught, not published in textbooks, nor recognized by any international standards bodies.

I can't think of too many scenarios that extended prefixes would be helpful. Using an atomic scale ruler to measure the universe?

**Comment by Modelmat** [comment]
That's a good point - I was needing them for Schwarzschild Radius Calculator.

Maybe add something like
```python
from pint import extended_units
```
Or something - I have no idea how to do that though

**Comment by Modelmat** [comment]
@onealj Hello? Could we have that maybe?

**Comment by hgrecco** [comment]
We can put them on an external file or maybe in a group

**Pull request closed without merging**
