### PR TITLE
support numpy's __array_ufunc__

### PR DESCRIPTION
**Pull request by tecki**
newer versions of numpy replace `__array_prepare__` and `__array_wrap__`
with the improved `__array_ufunc__`. This avoids some double-calculation
of data, and improves code readability.

### CODE REVIEW

**Comment by tecki** [comment]
The coverage has decreased, but this is actually expected: we have now two code paths, one taken by old (pre-1.13) versions of numpy, the other ones taken by the new versions. So some code paths seem untested, but actually they are, by the other numpy version. I don't know how to deal with that.

**Comment by wisp3rwind** [comment]
I think you could use `coverage erase`, `coverage run -p` and `coverage combine` as detailed in the links from this answer https://stackoverflow.com/a/19288889/3451198 to get accurate coverage reporting. Haven't done that myself before, so YMMV.

**Comment by hgrecco** [comment]
Sorry it took so long and thanks for the great patch. Hopefully this will allow us to support more numpy functions better.

**Pull request merged**
