### PR TITLE
Update with pandas interface authors

### LINKED ISSUE #694: Update authors
Trying to understand the new cool Pandas feature i spotted this:

```
    # I'm happy with both of these as long as Andrew and Zebedee are added on
    # but need to check with Pint Authors...
```
https://github.com/hgrecco/pint/blob/master/pint/pandas_interface/pint_array.py#L6

This should probably be removed and @znicholls and @andrewgsavage be added to AUTHORS?

### PR DESCRIPTION
**Pull request by znicholls**
closes #694 

@andrewgsavage can you add your email to this (you should be able to push directly to this branch)

### CODE REVIEW

**Comment by znicholls** [comment]
@andrewgsavage sorry I mucked this up whilst trying to work out what's going on with coverage can you add your email again please

**Comment by znicholls** [comment]
@hgrecco any idea what's going on with coverage?

**Comment by hgrecco** [comment]
I am merging this anyway until we find the issue

**Comment by hgrecco** [comment]
I have disabled coverage failure report until we fix this issue.

**Pull request merged**
