### PR TITLE
Fix parsing of units string with same canonalized name

### LINKED ISSUE #1441: Unit object gives wrong unit when mixing aliases
When creating a unit object with mixed aliases (`ureg.Unit('hour/hr')`), it returns a wrong unit. It seems like part of it gets ignored. This does not happen when creating a quantity as `ureg.Quantity('1 hour/hr')`.

Replicating code:
```
import pint
ureg = pint.UnitRegistry()
print(ureg.Unit('hour/hr'))       # prints "<Unit('1 / hour')>"

print(ureg.Quantity('1 hour/hr')) # prints "<Quantity(1.0, 'dimensionless')>"
```

In my model, the user sometimes uses units like "Gt CO2/yr" and "trillion USD/year". Costs per gigaton of CO2 become messed up because the "yr/year" doesn't disappear. I cannot switch to `Quantity`, since I use pint through the optimisation package Pyomo, which uses `Unit`.

### PR DESCRIPTION
**Pull request by jules-ch**
- [x] Closes #1441& #1142
- [x] Executed ``pre-commit run --all-files`` with no errors
- [x] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Review by keewis — APPROVED** [review]
looks good to me

**Comment by jules-ch** [comment]
Mypy support implicit `Optional` but explicit is prefered.

https://stackoverflow.com/questions/62732402/can-i-omit-optional-if-i-set-default-to-none

**Comment by hgrecco** [comment]
Looks good to me!

**Comment by jules-ch** [comment]
Thanks for the quick review !

**Pull request merged**
