### PR TITLE
Add the resulting exception of the operation

### PR DESCRIPTION
**Pull request by yuvallanger**
Should I maybe add more of the error message or would that be too much?

### CODE REVIEW

**Comment by hgrecco** [comment]
But comparing the id of the registries will result in False. What will raise an exception is operating between the two (for example adding q1 and q2)

**Comment by yuvallanger** [comment]
Woops! Sorry about that! A lesson for life:
Never send pull requests while being hurried away by a broom wielding barista with a fast approaching coffee shop closing time. You are going to make mistakes.

A question: I've tried:
```
q1, q2 = pint.UnitRegistry().meter, pint.UnitRegistry().meter

print(1 * q1 == 2 * q2)  # False
print(1 * q1 == 1 * q2)  # True
print(q1 == q1)  # True
print(q1 == q2)  # ValueError: Cannot operate with Unit and Unit of different registries.
```

Only the last one raises an exception.

**Comment by hgrecco** [comment]
In the first case you are comparing units, in the second Quantities. Is a bug, should raise a value error for all cases.

**Comment by hgrecco** [comment]
I have fixed the tutorial, the Unit comparison still needs fixing

**Pull request closed without merging**
