### PR TITLE
Exceptions overhaul

### LINKED ISSUE #912: Unit.__lt__ makes pprint crash
The vast majority of the implementations of (dis)equality methods in Python (``__lt__`` etc.) raise TypeError when a comparison doesn't make sense. Although this isn't explicitly mandated by the data model, it is a de facto standard.

pint, however, can raise DimensionalityError, which is a subclass of ValueError.
This breaks pprint.pformat, which tries to sort sets and frozensets beyond a certain size and graciously handles TypeError, but not arbitrary exceptions. pprint.pformat is invoked by unittest.TestCase.assertEqual when a comparison fails.

```python
import pprint
import pint

ureg = pint.UnitRegistry()
meter_units = ureg.get_compatible_units(ureg.meter)
hertz_units = ureg.get_compatible_units(ureg.hertz)
pprint.pformat(meter_units | hertz_units)
```
Output:
```
Traceback (most recent call last):
  File "lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-eecee46faec1>", line 1, in <module>
    pprint.pformat(units)
  File "lib/python3.6/pprint.py", line 58, in pformat
    compact=compact).pformat(object)
  File "lib/python3.6/pprint.py", line 144, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "lib/python3.6/pprint.py", line 167, in _format
    p(self, object, stream, indent, allowance, context, level + 1)
  File "lib/python3.6/pprint.py", line 236, in _pprint_set
    object = sorted(object, key=_safe_key)
  File "lib/python3.6/pprint.py", line 89, in __lt__
    return self.obj < other.obj
  File "pint/unit.py", line 219, in <lambda>
    __lt__ = lambda self, other: self.compare(other, op=operator.lt)
  File "pint/unit.py", line 215, in compare
    return self_q.compare(self._REGISTRY.Quantity(1, other), op)
  File "pint/quantity.py", line 78, in wrapped
    result = f(self, *args, **kwargs)
  File "pint/quantity.py", line 1274, in compare
    self.dimensionality, other.dimensionality)
pint.errors.DimensionalityError: Cannot convert from 'x_unit_Cu' ([length]) to 'becquerel' (1 / [time])
pprint.pformat(frozenset({Unit("m"), Unit("Hz")}))
```

### LINKED ISSUE #914: pint Exceptions can't be pickled
pint Exceptions cause a crash on pickle.loads.

```python
pickle.loads(pickle.dumps(DefinitionSyntaxError("foo")
# TypeError: __init__() missing 1 required positional argument: 'msg'

pickle.loads(pickle.dumps(RedefinitionError("foo", "bar")))
# TypeError: __init__() missing 2 required positional arguments: 'name' and 'definition_type'

pickle.loads(pickle.dumps(UndefinedUnitError))
# TypeError: __init__() missing 1 required positional argument: 'unit_names'

pickle.loads(pickle.dumps(DimensionalityError("a", "b", "c", "d")))
# TypeError: __init__() missing 2 required positional arguments: 'units1' and 'units2'

pickle.loads(pickle.dumps(OffsetUnitCalculusError("foo", "bar")))
# TypeError: __init__() missing 1 required positional argument: 'units1'
```

This is a problem for users of ``concurrent.futures.ProcessPoolExecutor``, ``dask.multiprocessing``, ``dask.distributed`` (not when using ``dask.array``), spark, etc.

The issue is caused by a short-sighted implementation of ``Exception.__reduce__``, which causes pickle.loads to invoke``type(self)(*self.args)``.

### PR DESCRIPTION
**Pull request by crusaderky**
- ``DefinitionSyntaxError`` subclasses SyntaxError (was ValueError)
- ``DimensionalityError`` and ``OffsetUnitCalculusError`` subclass TypeError (was ValueError); this fixes pprint - Closes #912 
- ``DefinitionSyntaxError`` and ``RedefinitionError`` are now accessible from the top-level package
- Ensure that all exceptions can be pickled without loss of data - Closes #914 
- General razionalization of the whole pint.errors module
- Thoroughly cover exception string representation with unit tests

### CODE REVIEW

**Comment by crusaderky** [comment]
@hgrecco Ready for review and merge

**Comment by hgrecco** [comment]
Looks good to me. But because is a breaking change, please add a line to CHANGES labeled `BACKWARDS INCOMPATIBLE CHANGE` so we do not forget. Also, a small summary in the docs with this rationale would be good.

**Comment by crusaderky** [comment]
@hgrecco updated CHANGES, see if you like it.

> Also, a small summary in the docs with this rationale would be good.

Not sure I understand what you mean? There's already a test in test_issues.py that verifies compatibility with pprint.

**Comment by hgrecco** [comment]
> Not sure I understand what you mean? There's already a test in test_issues.py that verifies compatibility with pprint.
When we update the docs, describing the Exception structure would be nice.

**Pull request merged**
