### PR TITLE
Switch Travis CI test configuration to pytest and add matplotlib tests

### LINKED ISSUE #897: Implement tests for matplotlib functionality
As discussed in #891, pint.matplotlib is currently lacking tests in the test suite. Adding those would be beneficial so that issues can be caught in pint and not downstream!

### PR DESCRIPTION
**Pull request by jthielen**
As discussed in #947, this PR switches Travis CI to use pytest for Pint's test suite instead of unittest. As a motivating example, basic tests for `pint.matplotlib` are added (which closes #897).

- [x] Closes #897, towards #947 (but does not fully resolve it)
- [x] Executed ``black -t py36 . && isort -rc . && flake8`` with no errors
- [x] The change is fully covered by automated unit tests
- ~~Documented in docs/ as appropriate~~
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by jthielen** [comment]
The switch to pytest seems to be working great, but the matplotlib tests are not matching the baselines I created locally. I'll be taking a look at those, and once I can figure out what is wrong with them, this should be ready for review.

**Comment by jthielen** [comment]
All the tests are passing now, so this should be ready for review and merge.

**Comment by hgrecco** [comment]
Just as a a reminder for the future. Now that pytest is available we could streamline some of the existing tests to make good use of it.

**Comment by westurner** [comment]
:+1: 

> @pytest.mark.parametrize might make it easier to identify the test failures by creating named test cases for each combination. 

ParametrizedTestCase:

https://github.com/hgrecco/pint/blob/2503f00762d1bc159ab196e2de93963f257629dd/pint/testsuite/parameterized.py

pytest.mark.parametrize:

https://github.com/pytest-dev/pytest/blob/8be9684ab23220cc85abb06e06414961667340b3/src/_pytest/python.py#L918-L922

https://github.com/pytest-dev/pytest/blob/8be9684ab23220cc85abb06e06414961667340b3/src/_pytest/python.py#L987-L990

**Pull request merged**
