### PR TITLE
Use application registry in docs

### PR DESCRIPTION
**Pull request by cpascual**
The application registry feature is not adequately advertised.
Improve this by using get_application_registry() instead of UnitRegistry()
throughout the docs (including README and docstrings) when that makes sense.
Also change the tutorial to recommend using it whenever possible.

See https://github.com/hgrecco/pint/issues/1273 for the motivation.

- [ ] Closes # (insert issue number)
- [ ] Executed ``pre-commit run --all-files`` with no errors
- [ ] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by cpascual** [comment]
Hi, I am getting [some doctest errors](https://github.com/hgrecco/pint/pull/1275/checks?check_run_id=2183721477), but I am not sure if they are related to my changes.

**Comment by hgrecco** [comment]
I am not sure that putting `ureg.get_application_registry` everywhere is a good idea but I might biased by my own history with pint. 

What I already know is that we should improve the correspondending [subsection](https://pint.readthedocs.io/en/stable/tutorial.html#using-pint-in-your-projects) (or even move it to its own section). This should include the rationale that I gave in #1273 and maybe a small example (e.g. project 1, project 2 ..)

Going back to the readme and docs, my fear is that we are changing the suggested way to use it too quickly and confuse existing users. My suggestions would be to do a gradual rollout. Example: we put the `get_application_registry` in the readme and cos as a note after we show how to instantiate the registry and I see how it plays off. But, as I said, I might be dead wrong so I would be happy to hear others peoples thoughts.

**Comment by cpascual** [comment]
I completely defer it to your judgement, @hgrecco since I have only a very biased perspective on the use of pint. 

I created this PR just because it was simpler than trying to explain my proposed changes, but I don't mind at all if it is partially or completely edited.

My point of view: I like the "radical" change (as proposed) because the full benefit of the application registry comes, IMHO, when its use is generalized (i.e. when most pint-enabled projects play along well with the rest)

**Comment by andrewgsavage** [comment]
the docs have been reorganised since this so I'll close it

**Pull request closed without merging**
