### PR TITLE
to_compact now returns self for NaN and infinite magnitudes

### PR DESCRIPTION
**Pull request by emilienkofman**
I think it makes sense for infinity. For NaN magnitudes this is discutable.

### CODE REVIEW

**Comment by hgrecco** [comment]
Sounds good to me but this change will fail for arrays
```python
>>> import numpy as np
>>> x = np.asarray([1,2,3])
>>> import math
>>> math.isnan(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: only length-1 arrays can be converted to Python scalars
```

**Comment by hgrecco** [comment]
By the way, the current version in master will also fail:
```python
>>> bool(x==0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by emilienkofman** [comment]
Ah ok so I'll try to elaborate something better, and eventually add a unit test also. Thanks for those tips.

**Comment by hgrecco** [comment]
Actually, thank you. Your commit made me realize that the current implementation is buggy.

**Comment by emilienkofman** [comment]
Hi, I was just trying to figure out what it should do for arrays, but then I realized that obviously I cannot apply `to_compact` to each element since then they could be associated to different magnitudes. So I guess when the magnitudes is a numpy array it should also return self? Maybe it could also raise a warning to tell why this could not work?

**Comment by hgrecco** [comment]
I think the warning idea and returning self is a good one. Another option is calculating the median (or something like that), find the most appropriate units and the transforming all values to that.

**Comment by emilienkofman** [comment]
Ok I implemented the warning option, which is better in my opinion because as I understand, the magnitude could even be non numerical (I don't know if it makes much sense though). So, it raises a warning if the magnitude is not numerical (and returns self) which includes numpy arrays, lists, and so on. For some reason I deleted my repository and created a new fork, do you know how I can submit my changes here? The commit is here https://github.com/emilienkofman/pint/commit/afff318e62011f5852672fa06234c808e0d543d6

**Comment by hgrecco** [comment]
This was fixed thanks to #340

**Comment by hgrecco** [comment]
Thanks a lot for your work

**Pull request closed without merging**
