### PR TITLE
Fix custom formatters needing registry

### LINKED ISSUE #2009: What does `registry=None` mean in custom formatter ?
Hi!

With pint 0.24, the internal workings of `register_unit_format` have changed and the `registry` argument of the wrapped function can now be "None". I do not see in the doc the meaning of that new possible value. Wouldn't a `Unit` object always be related to a registry, even if it's the default one ?

This is causing issues in `cf-xarray` (and downstream) for example (xarray-contrib/cf-xarray#507) where we used `registry` to convert the `UnitContainer` back to a `Unit` (see https://github.com/xarray-contrib/cf-xarray/blob/24dd81b2748db59c3ede68735a200b63b8a3d2d2/cf_xarray/units.py#L17-L38)

EDIT: Also, the way  `register_unit_format` is written, wouldn't `registry` _always_ be None ?

### PR DESCRIPTION
**Pull request by aulemahal**
- [x] Closes #2009
- [x] Executed `pre-commit run --all-files` with no errors
- [x] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

Fixes #2009 according to the suggestions in the thread. I also added a note to the doc to describe the arguments passed to the custom formatters. And added a line to the test.

### CODE REVIEW

**Comment by hgrecco** [comment]
@aulemahal Have you tested against `cf-xarray`?  Does it fix the issue?

**Comment by aulemahal** [comment]
Yes it does!

```python3
from cf_xarray import units

q = units.units.Quantity(1, 'm')

f"{q.units:cf}"
```
fails with the current `master` and works with this branch.

**Comment by hgrecco** [comment]
Then I think we can merge it and release 0.24.1 What do you think @andrewgsavage ?

**Comment by andrewgsavage** [comment]
Yes , once I get the formatting of dimensionless to match previous behaviour

**Pull request merged**
