### PR TITLE
Fix wraps example typo

### LINKED ISSUE #1088: Wraps example typo
Hi all, 

This example from the docs fails on master:
```python
@ureg.wraps(ureg.second, (ureg.meters, ureg.meters/ureg.second**2))  # <- Missing None here?
def calculate_time_to_fall(height, gravity=Q_(9.8, 'm/s^2'), verbose=False):
    """Calculate time to fall from a height h.

    By default, the gravity is assumed to be earth gravity,
    but it can be modified.

    d = .5 * g * t**2
    t = sqrt(2 * d / g)
    """
    t = sqrt(2 * height / gravity)
    if verbose: print(str(t) + " seconds to fall")
    return t

lunar_module_height = Q_(22, 'feet') + Q_(11, 'inches')
calculate_time_to_fall(lunar_module_height, verbose=True)
```

The error is `TypeError: calculate_time_to_fall takes 3 parameters, but 2 units were passed`. I believe this is due to the missing `None` in the tuple for the input parameters. So the first line should be 
```python
@ureg.wraps(ureg.second, (ureg.meters, ureg.meters/ureg.second**2, None))
...
```

### PR DESCRIPTION
**Pull request by dimapu**
- [x] Closes #1088
- [x] Executed ``black -t py36 . && isort -rc . && flake8`` with no errors
- [ ] The change is fully covered by automated unit tests
- [ ] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by hgrecco** [comment]
Plase run `black -t py36 . && isort -rc . && flake8 with no errors`

**Comment by dimapu** [comment]
> 
> 
> Plase run `black -t py36 . && isort -rc . && flake8 with no errors`

Done!

```
All done! ✨ 🍰 ✨
50 files left unchanged.
Skipped 1 files
```

**Comment by keewis** [comment]
@hgrecco, the build failure is a network error, rerunning the CI should fix this

**Pull request merged**
