### PR TITLE
Find minimal unit using preferred units - "to_preferred"

### PR DESCRIPTION
**Pull request by BlueOrigin**
### Abstract
Finding the minimal representation of some unit, with a disposition towards preferred units, is an NP-complete problem. This patch frames it as an Integer Programming problem using the `mip` package. The new `test_to_preferred` function in `test_quantity.py` doubles as a demonstration.

- [x] Closes N/A
- [x] Executed ``pre-commit run --all-files`` with no errors
- [x] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### Principle
We often have units that we prefer for printing or reporting physical quantities. For instance, $\mathrm{watts}$ may be easier to read than $\mathrm{kg\ m^2\ s^{-3}}$. In some circumstances, we may also prefer $\mathrm{feet}$ over $\mathrm{meters}$. In the first case

| Unit | Sum of exponent magnitudes |
| ---- | ------------------------------------- |
| $\mathrm{W^1}$ | $\| 1 \| = 1$ |
| $\mathrm{kg^1 m^2 s^{-3}}$ | $\|1\| + \|2\| + \|-3\| = 6$ |

A unit with a small sum of exponent magnitudes is desirable. In the second case, $\mathrm{meters}$ has more weight than $\mathrm{feet}$. (In the table below, "100" is chosen for demonstration only. In the implementation, a sufficiently large number is chosen such that undesirable units will always cost more than preferred, regardless of either unit's exponent.)

| Unit | Weighted sum of exponent magnitudes |
| ---- | ----------- |
| $\mathrm{ft^1 s^{-2}}$ | $\|1\| + \|-2\| = 3$ |
| $\mathrm{m^1 s^{-2}}$ | $100 * \|1\| + \|-2\| = 102$ |

This is the cost function to minimize. The units that are chosen, and the exponents for each, must result in the same dimensionality as the original dimensions. For instance, $\mathrm{watts}$ has dimensionality $Mass^1 Length^2 Time^{-3}$, and is a viable conversion for $\mathrm{kg^1 m^2 s^{-3}}$. This is the constraint for the minimization.

### Minimization
Given
- A quantity $Q$
- Functions $l, t, c ... m$ which take a unit or quantity and return the integer exponent of the Length, Time, Current ... Mass dimensions.
- A set of preferred units $P$
- The weight function $\displaylines{w(unit) = \begin{cases}unit \in P, &1 \\\\ else, & \text{a large natural number} \end{cases}}$
- A vector of candidate units $[U_1, U_2 ... U_n]$ (e.g. "kilogram", "seconds", "psf")
- and vector $[L, T, C ... M] = [l(Q), t(Q), c(Q) ... m(Q)]$

Find the integer exponents of units $U_1, U_2 ... U_n$ and call them vector $[x_1, x_2 ... x_n]$ such that
$$[x_1, x_2 ... x_n] \times \begin{bmatrix}l(U_1) & t(U_1) & c(U_1) & \cdots & m(U_1) \\\\ l(U_2) & t(U_2) & c(U_2) & \cdots & m(U_2) \\\\ \vdots & \vdots & \vdots & \ddots & \vdots \\\\ l(U_n) & t(U_n) & c(U_n) & \cdots & m(U_n) \end{bmatrix} = [L, T, C ... M]$$
and
$$\sum_{i=1}^n \|x_i\| w\(U_i)$$
is minimized.

### CODE REVIEW

**Comment by schneems** [comment]
This is very thoroughly commented. Thanks for all the work here. 

I'm curious what the maintainers think. Would you be interested in this feature? Can you trigger the workflow runs?

**Comment by hgrecco** [comment]
I actually like the proposal a lot, and I thank the effort to explain here the idea and its implementation. As it is a rather large piece of code, I am trying to see it in action. I would suggest that it would be nice to add here some examples showing it in action for a bunch of units. 

I am also wondering how does using MIPS compares with optimization methods provided by SciPy. I was under the impression that solving integer programming problems was added to SciPy, but I might be wrong as I have done very little in this field.

**Comment by blewis2-blue** [comment]
> add here some examples showing it in action

I'll find some time in the next several days to generate some more examples.

> I am also wondering how does using MIPS compares with optimization methods provided by SciPy. I was under the impression that solving integer programming problems was added to SciPy, but I might be wrong as I have done very little in this field.

Looking at https://docs.scipy.org/doc/scipy/reference/optimize.linprog-highs.html it indeed does integer programming, but only in the form outlined in the docs. The challenge is the absolute value in the cost function, and I used mip's proxy-variable capability to model that. There may be a workaround involving many invocations of `linprog`. I haven't tested it, but I suspect the performance impact would be significant because the number of calls would grow exponentially with the number of considered units.

**Comment by SimonHeybrock** [comment]
Very interesting! How would `to_preferred` deal with cases where the preferred unit depends on the context? As a concrete example, we prefer `angstrom` for wavelength measurements but at the same time prefer `meter` for describing the sensor position.

**Comment by andrewgsavage** [comment]
I can see myself using this of to_reduced_units. It requires a bit more set up - defining a list of preferred_units at the start of a file, but gives the desired units. For example:

```python3
preferred_units = [
            ureg.m,  # distance      L
            ureg.kg,  # mass          M
            ureg.s,  # duration      T
            ureg.N,  # force         L M T^-2
            ureg.Pa,  # pressure      M L^−1 T^−2
            ureg.W,  # power         L^2 M T^-3
]
pressure = (Q_("1 N") * Q_("1 m**-2"))
pressure.to_preferred(preferred_units)
1.0 pascal

pressure.to_reduced_units()
1.0 newton/meter2
```
There is the issue when you're working with quantities that have the same dimensionality, like torque and energy. 
```python3
torque = (Q_("1 N") * Q_("1 m"))
torque.to_preferred(preferred_units)
1 meter newton

torque.to_reduced_units()
1 meter newton
ureg.J

energy = (Q_("1 W") * Q_("1 s"))
energy.to_preferred(preferred_units)
1.0 meter newton

energy.to_reduced_units()
1 second watt


# Adding joules to preferred_units will cause to_preferred to convert to joules instead of newton meters.
preferred_units.append(ureg.J)
torque.to_preferred(preferred_units)
1.0 joule

energy.to_preferred(preferred_units)
1.0 joule
```

In the future it would be great to have an option to autoconvert to prefered units like for to_reduced_units. This could be done with attribute on the ureg for its preferred_units.

**Comment by hgrecco** [comment]
I agree with @andrewgsavage . @blewis2-blue if using scipy is too cumbersome or slow, then we stick with your solution. The only reason I proposed scipy is that it is a common package in most scientific python installations. So people will usually get your functionality without requiring an extra thing.

**Comment by blewis2-blue** [comment]
@SimonHeybrock You'll want to pass in a different collection of preferred units depending on the context.

@hgrecco  Here's a small script to generate examples. It will print `Here's a nice one:` when the conversion has changed all the sub-units.

```
import operator
import random
from functools import reduce

import pint

ureg = pint.UnitRegistry()
Q_ = ureg.Quantity

units = [ureg.Unit(u) for u in sorted({str(u) for u in ureg._units.values()})]

def get_some_units():
    return random.sample(units, random.randint(1, 5))

def shorty(value):
    try:
        return f"{value:~}"
    except ValueError:
        return f"{value}"

for _ in range(100):
    magnitude = random.randint(0, 1000) / 100
    preferred_units = get_some_units()
    unit = reduce(operator.mul, get_some_units(), ureg.Unit(""))
    quantity = Q_(magnitude, unit)

    try:
        preferred = quantity.to_preferred(preferred_units)

        result_parts = set(preferred.units._units)
        if not result_parts.intersection(unit._units) and result_parts.intersection(map(str, preferred_units)):
            print("Here's a nice one:")

    except pint.errors.DimensionalityError:
        preferred = "DimensionalityError"
    
    preferred_units_str = ", ".join(f"""Unit("{shorty(u)}")""" for u in preferred_units)
    print(f"""Q_("{shorty(quantity)}").to_preferred([{preferred_units_str}]) == {shorty(preferred)}""")
```

Here's some output:

```
Q_("4.02 R * V_it * cu_ft * yd * µ").to_preferred([Unit("γ"), Unit("tex_didot"), Unit("fathom"), Unit("a_u_intensity")]) == 5.088288768794959e-09 R * V_it * fathom ** 5
Q_("9.19 g_e * gf * stone").to_preferred([Unit("tex_point"), Unit("planck_length"), Unit("imperial_fluid_scruple")]) == -18.401314407091924 gf * stone
Q_("4.72 eV * k * mmHg * refrigeration_ton").to_preferred([Unit("pica"), Unit("mil"), Unit("min")]) == 4.72 eV * k * mmHg * refrigeration_ton
Here's a nice one:
Q_("6.04 ft_lb").to_preferred([Unit("PPCM"), Unit("tTNT"), Unit("abC"), Unit("li"), Unit("imperial_gal")]) == 1.9572515315300327e-09 tTNT
Q_("5.5 C * H2O * PSH * stone * σ_e").to_preferred([Unit("kt")]) == 2.964077699762872e-26 A * PSH * stone ** 2 / kt
Here's a nice one:
Q_("7.69 a_u_time").to_preferred([Unit("abF"), Unit("tropical_month"), Unit("ft_lb")]) == 7.879920848092712e-23 tropical_month
Q_("0.6 Da * planck_time").to_preferred([Unit("U"), Unit("lb"), Unit("dwt"), Unit("At")]) == 6.406508483707517e-25 dwt * planck_time
Q_("7.8 St * gi * ζ").to_preferred([Unit("wien_x")]) == 233838117240.0 St * gi
Here's a nice one:
Q_("0.38 metric_horsepower * mps * pc * α").to_preferred([Unit("UK_ton"), Unit("S"), Unit("K_alpha_Mo_d_220"), Unit("ly"), Unit("cal_15")]) == 3.650063977439799e+18 cal_15 ** 2 / UK_ton
Q_("6.62 V * abΩ").to_preferred([Unit("tex_didot"), Unit("µmol"), Unit("Xu_Mo"), Unit("floz"), Unit("statV")]) == 6.62 V * abΩ
Q_("1.54 Ah * Rd * faraday_constant * µ_N").to_preferred([Unit("k_C"), Unit("ksi"), Unit("cal_it"), Unit("inch_Hg_60F")]) == 5544000000.0 A * faraday_constant * µ_N
Here's a nice one:
Q_("6.36 A * fur * Ω_90 * ζ").to_preferred([Unit("µm"), Unit("abV"), Unit("US_cwt")]) == 3.8356378280696214e+27 abV * µm
Q_("2.42 oil_bbl * shake").to_preferred([Unit("PSH"), Unit("cm"), Unit("pdl"), Unit("U"), Unit("tex_didot")]) == 7234173880.174006 shake * tex_didot ** 3
Here's a nice one:
Q_("8.85 N * century * leap_year * pixel").to_preferred([Unit("slpm"), Unit("sq_in"), Unit("dots_per_inch")]) == 3.4770292892220476e+22 dots_per_inch * g * sq_in
Q_("5.09 a * r_e").to_preferred([Unit("scruple"), Unit("tex_pica"), Unit("yd"), Unit("abΩ")]) == 1.5686041404680905e-14 a * yd
Q_("5.09 S").to_preferred([Unit("A_it"), Unit("atm"), Unit("E_h"), Unit("fps")]) == 5.09 S
Here's a nice one:
Q_("4.12 blob * kg").to_preferred([Unit("shake"), Unit("pp"), Unit("atm_l"), Unit("km"), Unit("Δ°C")]) == 7.027756260785477e+42 atm_l ** 2 * shake ** 4 / km ** 4
Q_("0.52 rads").to_preferred([Unit("imperial_fluid_scruple"), Unit("sr"), Unit("century"), Unit("cal_it")]) == 0.52 rads
Q_("3.15 thm").to_preferred([Unit("statΩ"), Unit("th"), Unit("°C")]) == 3.15 thm
Here's a nice one:
Q_("7.31 Ba * Pa * abΩ * ζ").to_preferred([Unit("R_K"), Unit("Bq"), Unit("wien_frequency_displacement_law_constant"), Unit("a_u_force"), Unit("hp")]) == 8.394591075674875e+50 Bq ** 4 * R_K * a_u_force ** 6 / hp ** 4
Q_("2.16 bit * den * km * rd * sidereal_day").to_preferred([Unit("bar"), Unit("N")]) == 1086309372.6187453 N * den * sidereal_day / bar
Here's a nice one:
Q_("0.86 cooling_tower_ton * mi").to_preferred([Unit("cm"), Unit("shake"), Unit("Ω_US"), Unit("abV"), Unit("hand")]) == 5.99146216243872e+23 abV ** 2 * hand / Ω_US
Q_("9.1 lm * mol * stone * Δ°C").to_preferred([Unit("stere"), Unit("beer_bbl"), Unit("G"), Unit("mil")]) == 9.1 lm * mol * stone * Δ°C
Q_("2.2 Δ°Re").to_preferred([Unit("electrical_horsepower"), Unit("abV"), Unit("ton")]) == 2.2 Δ°Re
Here's a nice one:
Q_("2.09 H_90").to_preferred([Unit("K_J"), Unit("St"), Unit("Rd"), Unit("u")]) == 81164.12503529691 / K_J ** 2 / Rd / St / u
Q_("7.73 A_90 * tropical_year").to_preferred([Unit("Da")]) == 7.73 A_90 * tropical_year
Here's a nice one:
Q_("1.91 µ_B").to_preferred([Unit("biot_turn"), Unit("dTt"), Unit("thm"), Unit("m_n"), Unit("Ne")]) == 2.2019597680240687e+23 Ne ** 2 * biot_turn * m_n ** 2
Here's a nice one:
Q_("1.93 VA").to_preferred([Unit("kt"), Unit("statA")]) == 992877777.7777778 statA ** 2 / kt
Q_("8.81 R_∞ * kat * mg * statV * stere").to_preferred([Unit("a_u_time"), Unit("wien_x"), Unit("synodic_month"), Unit("statV")]) == 3.7891726093326867 m * mol * statV ** 3 * synodic_month
Q_("5.94 wien_x * γ").to_preferred([Unit("gr"), Unit("pk"), Unit("H_90")]) == 29.492778536561 γ
Q_("7.6 didot * long_hundredweight * svedberg * wien_wavelength_displacement_law_constant * Δ°C").to_preferred([Unit("psi"), Unit("cu_yd"), Unit("T"), Unit("kip"), Unit("cm_1")]) == 0.9859791941289185 long_hundredweight * svedberg * wien_wavelength_displacement_law_constant ** 2
Q_("5.44 cmHg * kg * ksi * tex_pica").to_preferred([Unit("sq_ft"), Unit("Mx"), Unit("A"), Unit("K_J90")]) == 8.178093185896151e+28 A * Mx ** 2 * kg / K_J90 / sq_ft ** 3
Q_("7.24 A_US * Ba * Bd * oct * sq_deg").to_preferred([Unit("dgal"), Unit("ℎ"), Unit("Cl")]) == DimensionalityError
Q_("3.68 sidereal_day").to_preferred([Unit("acre_foot")]) == 3.68 sidereal_day
Q_("5.04 UK_ton * synodic_month").to_preferred([Unit("atm_l"), Unit("erg"), Unit("ton")]) == 5.644800000000001 synodic_month * ton
Q_("4.85 bbl * leap_year * tex_cicero").to_preferred([Unit("Ω_US"), Unit("K_alpha_Cu_d_220")]) == 4.85 bbl * leap_year * tex_cicero
Q_("4.2 b * gi * °Re").to_preferred([Unit("water_4C"), Unit("d_220")]) == DimensionalityError
Q_("8.58 arcmin * dpi").to_preferred([Unit("Ω_it"), Unit("dyn")]) == 0.0024958208303518916 dpi
Q_("5.66 RKM").to_preferred([Unit("F_90"), Unit("fathom")]) == 5.66 RKM
Q_("0.16 D * cm * lbf * planck_current * tex_pica").to_preferred([Unit("lambert"), Unit("arcsec"), Unit("fur"), Unit("Wb")]) == 1.6674674194130273e-10 D * fur ** 2 * lbf * planck_current
Q_("7.47 eon * pk * sft").to_preferred([Unit("a_u_intensity")]) == 7.47 eon * pk * sft
Q_("2.26 arcmin * sq_ft * Δ°Re").to_preferred([Unit("US_ton"), Unit("cmH2O"), Unit("R"), Unit("planck_mass"), Unit("pt")]) == 0.0006574073515845308 sq_ft * Δ°Re
Here's a nice one:
Q_("2.4 RKM * buckingham * in * kph").to_preferred([Unit("square_survey_mile"), Unit("abC"), Unit("s")]) == 3.188187887358058e-58 abC * square_survey_mile ** 3 / s ** 3
Here's a nice one:
Q_("4.83 ct").to_preferred([Unit("Da"), Unit("fifth"), Unit("G"), Unit("kph"), Unit("k_C")]) == 5.8173879761703645e+23 Da
Q_("8.47 imperial_bbl * toz").to_preferred([Unit("imperial_cp"), Unit("lambert"), Unit("au")]) == 4878.72 imperial_cp * toz
Here's a nice one:
Q_("2.03 H_90 * Ry").to_preferred([Unit("F_90"), Unit("cables_length"), Unit("week")]) == 9.188200159512791e-20 cables_length ** 2 * g / F_90
Q_("3.1 PPCM * statH * Δ°Re").to_preferred([Unit("Ah"), Unit("imperial_bu")]) == 3.1 PPCM * statH * Δ°Re
Q_("1.67 bpp * common_year * oil_bbl * particle * psi").to_preferred([Unit("R_K")]) == 1.67 common_year * oil_bbl * particle * psi / pixel
Here's a nice one:
Q_("7.74 sidereal_month * sq_deg").to_preferred([Unit("Ta"), Unit("J"), Unit("d_220"), Unit("a"), Unit("cal_15")]) == 0.00017636507135744187 a
Here's a nice one:
Q_("3.49 cicero * g_0 * imperial_gal * m_u * µm").to_preferred([Unit("ft"), Unit("electrical_horsepower"), Unit("µmol")]) == 1.8102316782171793e-37 electrical_horsepower * ft ** 4 * s
Q_("8.84 A_it * e * force_long_ton * px * sq_yd").to_preferred([Unit("kph"), Unit("dpi")]) == 3.551752680871644 A_it * dpi * e * force_long_ton
Q_("4.71 K_J * kg * long_hundredweight * px").to_preferred([Unit("Hg_60F")]) == 0.09271225490096192 K_J * long_hundredweight ** 2 * px
Orbit 0:  1 2
Here's a nice one:
Q_("7.96 µ_0").to_preferred([Unit("km"), Unit("C_90"), Unit("µg"), Unit("K_alpha_W_d_220"), Unit("gr")]) == 0.00015436730019760374 gr * km / C_90 ** 2
Here's a nice one:
Q_("4.2 F_90 * cP * gf * µ_B").to_preferred([Unit("li"), Unit("Bi"), Unit("F_90")]) == 3.819772711300986e-28 Bi ** 3 * g * s
Q_("1.4 V_90 * W * dm * tbsp * wien_u").to_preferred([Unit("statA"), Unit("mi")]) == 8.707157128746003e-19 V_90 * W * mi ** 4
Here's a nice one:
Q_("0.38 imperial_gi * sidereal_month * sq_yd").to_preferred([Unit("PSH"), Unit("hand"), Unit("cps"), Unit("mps"), Unit("bar")]) == 9842295.326633485 hand ** 5 / cps
Q_("7.31 A_it * sv").to_preferred([Unit("abS"), Unit("atm"), Unit("arcmin"), Unit("sq_in"), Unit("rad")]) == 7.31 A_it * sv
Q_("1.24 Tt * acre_foot * ftH2O * statΩ").to_preferred([Unit("wien_wavelength_displacement_law_constant"), Unit("boiler_horsepower")]) == 45718575298126.08 Tt * g / statΩ
Q_("1.75 gr * mi * sidereal_year * α").to_preferred([Unit("kgf"), Unit("jig"), Unit("imperial_cp")]) == 0.012770366996287422 gr * mi * sidereal_year
Here's a nice one:
Q_("1.45 px * Ω_US").to_preferred([Unit("cm_1"), Unit("cmil"), Unit("thm"), Unit("S")]) == 0.03838357380208333 / S / cm_1
Q_("3.36 H * H_90 * a_u_time * mi").to_preferred([Unit("planck_time"), Unit("at"), Unit("den"), Unit("particle"), Unit("g_0")]) == 8.511675145176137e+115 H ** 2 * g_0 * planck_time ** 3
Q_("0.55 PSH").to_preferred([Unit("cps"), Unit("cal")]) == 0.55 PSH
Q_("8.08 dTt * mps * oil_bbl * scaled_point").to_preferred([Unit("ft_lb")]) == 3.1959922185722687e-15 ft_lb * oil_bbl / mps
Q_("4.72 Nm * cps * sidereal_day * toe").to_preferred([Unit("torr"), Unit("wien_frequency_displacement_law_constant"), Unit("imperial_floz"), Unit("U")]) == 4.4949975122392965e+18 Nm * imperial_floz * torr
Q_("6.83 blob * cicero").to_preferred([Unit("square_league")]) == 6.83 blob * cicero
Q_("6.5 K_alpha_Mo_d_220 * at * imperial_floz * rads * Δ°Re").to_preferred([Unit("Rd"), Unit("Bd"), Unit("Å_star")]) == 6.821861820766533e+43 Bd ** 2 * at * Å_star ** 5 * Δ°Re
Q_("7.66 H2O * yd").to_preferred([Unit("dry_barrel"), Unit("force_long_ton")]) == 7.66 H2O * yd
Q_("0.92 boiler_horsepower").to_preferred([Unit("γ"), Unit("µ_0")]) == 0.92 boiler_horsepower
Q_("5.53 Bi * cooling_tower_ton * rps * tex_point * thm").to_preferred([Unit("UK_cwt"), Unit("rpm")]) == 833904.3539688749 Bi * cooling_tower_ton ** 2 * tex_point
Q_("1.68 c_2 * imperial_pk").to_preferred([Unit("Pa"), Unit("acre_foot"), Unit("sv"), Unit("kip"), Unit("Fr")]) == 1.2383458179959173e-05 acre_foot * c_2
Q_("9.63 gf").to_preferred([Unit("pt"), Unit("ct"), Unit("inHg"), Unit("ln10")]) == 9.63 gf
Q_("7.12 K_J * rd").to_preferred([Unit("eon"), Unit("a_u_intensity"), Unit("mi")]) == 0.022250044500088998 K_J * mi
Q_("0.14 PPCM * Rd * at * darcy * sq_deg").to_preferred([Unit("Ne"), Unit("Pa"), Unit("V"), Unit("Ω_it")]) == 4.075519484545836e-16 V ** 2 * pixel / darcy / Ω_it
Here's a nice one:
Q_("4.67 dBu").to_preferred([Unit("PSH"), Unit("d"), Unit("°C"), Unit("UK_force_ton"), Unit("ℎ")]) == 3.301957320820673e+37 ℎ / d ** 2
Q_("9.59 Wh * a_u_force * cc * imperial_bbl * statH").to_preferred([Unit("µ_B")]) == 12930.611540139651 Wh * cc ** 2 * g
Here's a nice one:
Q_("5.51 fathom").to_preferred([Unit("kt"), Unit("imperial_minim"), Unit("V_it"), Unit("century")]) == 2585.5905039313775 imperial_minim ** 0.333333
Q_("7.65 Bd").to_preferred([Unit("ζ"), Unit("px"), Unit("cal_15"), Unit("Cl")]) == 7.65 Bd
Q_("3.49 Nm * blob * nit").to_preferred([Unit("erg")]) == 611192.6550102028 m * nit
Q_("4.06 H * Mx * cc").to_preferred([Unit("G_0"), Unit("wien_frequency_displacement_law_constant"), Unit("u")]) == 4.06 H * Mx * cc
Q_("3.63 P * at * oil_bbl * yd").to_preferred([Unit("eon"), Unit("den")]) == 9.206995453557906e+63 den * g * oil_bbl / eon ** 3
Here's a nice one:
Q_("6.18 acre").to_preferred([Unit("abC"), Unit("kat"), Unit("R_∞")]) == 3.0117344302137216e+18 / R_∞ ** 2
Q_("7.96 US_cwt").to_preferred([Unit("kps"), Unit("π")]) == 7.96 US_cwt
Q_("1.09 UK_force_ton * VA * ftH2O * statWb").to_preferred([Unit("m_e"), Unit("dBu"), Unit("G"), Unit("Wb")]) == DimensionalityError
Here's a nice one:
Q_("1.78 tex_point").to_preferred([Unit("kat"), Unit("li"), Unit("abF"), Unit("µl")]) == 0.0031098246195174384 li
Here's a nice one:
Q_("8.98 Tj * dTt").to_preferred([Unit("inHg"), Unit("mi"), Unit("g_e"), Unit("Ci")]) == 5.055646116869033e+24 inHg ** 2 / Ci ** 4
Q_("4.53 Ci * cmHg * erg * stilb").to_preferred([Unit("rads"), Unit("Mx")]) == 4.53 Ci * cmHg * erg * stilb
Q_("2.72 common_year").to_preferred([Unit("mol"), Unit("eV"), Unit("gf"), Unit("m_u"), Unit("inch_H2O_39F")]) == 2.72 common_year
Q_("2.21 a_0 * faraday_constant * sq_deg * °C * Δ°Re").to_preferred([Unit("svedberg")]) == DimensionalityError
Q_("6.22 synodic_month").to_preferred([Unit("planck_current"), Unit("statV")]) == 6.22 synodic_month
Q_("3.67 Φ_0").to_preferred([Unit("sq_ft"), Unit("fifth"), Unit("qt"), Unit("imperial_qt"), Unit("long_ton")]) == 3.67 Φ_0
Q_("6.85 Sv * cps * force_long_ton").to_preferred([Unit("ksi"), Unit("tex_didot"), Unit("At")]) == 69997.11295137224 Sv * cps * ksi * tex_didot ** 2
Q_("6.41 Mx * li * oil_bbl").to_preferred([Unit("svedberg"), Unit("C_90"), Unit("min")]) == 6.41 Mx * li * oil_bbl
Q_("0.95 Da * au * k_C * rhe * turn").to_preferred([Unit("St")]) == 1.482784314228859e-10 St * k_C * s ** 2
Q_("7.94 a_u_force * k").to_preferred([Unit("force_ton"), Unit("E_h"), Unit("dyn")]) == 0.06541546457601759 dyn * k
Q_("5.55 m * planck_time * scaled_point").to_preferred([Unit("imperial_gal"), Unit("pt"), Unit("mil"), Unit("K"), Unit("K_J")]) == 6.290216183690532e-05 planck_time * pt / m
Q_("6.01 in * m_p * ħ").to_preferred([Unit("cm"), Unit("ha"), Unit("kg"), Unit("ly"), Unit("nit")]) == 2.698865884394241e-44 kg * ly * ħ
Q_("4.81 bag").to_preferred([Unit("px"), Unit("cp"), Unit("Gb")]) == 4.81 bag
Here's a nice one:
Q_("0.55 Tj").to_preferred([Unit("fathom"), Unit("dr"), Unit("sq_in")]) == 0.019555594666744898 dr / fathom
Here's a nice one:
Q_("6.46 pc").to_preferred([Unit("Xu_Cu")]) == 1.9892161671700974e+30 Xu_Cu
Q_("3.88 F * avogadro_number * eu * ftH2O * shake").to_preferred([Unit("oct"), Unit("bag")]) == 2.33659061488e+24 F * eu * ftH2O * shake
```

**Comment by andrewgsavage** [comment]
Is there anything preventing this being merged? It would have been nice to have this in the last release.

**Comment by OrangeChannel** [comment]
Any progress on this? I'd really like to be able to use this along with the new `percent` addition.

> I haven't tested it, but I suspect the performance impact would be significant because the number of calls would grow exponentially with the number of considered units.

Is the scipy issue still blocking?

**Comment by blewis2-blue** [comment]
@hgrecco If there's still interest in the feature I can merge from upstream (it can't be done automatically anymore) and investigate @OrangeChannel's issue... but I don't want to chase upstream forever. Let me know if there's something you're still looking for in order to move this forward and get it landed.

**Comment by andrewgsavage** [comment]
@hgrecco could this get included in the new release?

**Comment by hgrecco** [comment]
@andrewgsavage is merged! It is very likely that I will move part of the code out of the `PlainQuantity` class (is not so Plain anymore!) and into another facet. I would like Plain to be as simple as possible with the bare minimum to create and do math. I think that `to_compact`, `to_preferred`, and `to_reduced_units` belongs elsewhere.

We should document all this!

Great job Everyone!! 🎉

**Comment by MichaelTiemannOSC** [comment]
Several folks are interested in "as simple as possible, but not simpler", specifically when it comes to maintaining mass units:

```
Q_(1.0, "t CO2e / (t Steel)") # we like this
Q_(1.0, "CO2e / Steel") # we don't like this
```

Is there a simple way to tell the optimizer that when it sees tons of a substance, it's OK to convert that to some completely different unit (if there's an interesting complex simplification to be done), but cancelling tons over tons "just because" is forbidden?

**Comment by blewis2-blue** [comment]
> Several folks are interested in "as simple as possible, but not simpler", specifically when it comes to maintaining mass units:
> 
> ```
> Q_(1.0, "t CO2e / (t Steel)") # we like this
> Q_(1.0, "CO2e / Steel") # we don't like this
> ```
> 
> Is there a simple way to tell the optimizer that when it sees tons of a substance, it's OK to convert that to some completely different unit (if there's an interesting complex simplification to be done), but cancelling tons over tons "just because" is forbidden?

I suspect the reason it doesn't work like you're expecting is that, just like how `CO2e per Steel" isn't a unit of measure, "a steel" isn't a unit of measure. I don't know if putting non-units like that is valid Pint usage. If it is, then an issue should be created in the [Pint bug tracker](https://github.com/hgrecco/pint/issues). The dimensionality of that quantity is mass^0, and that's preserved. That said, there are probably workarounds you could try. Here are some I can think of:

1. Make a TonsOfSteel unit (or maybe t_steel, your preference) and use it instead of `t Steel`. 
1. Before you call to_preferred, take note of the occurrences of unbalanced units and replicate them afterwards.
1. Use variable names to describe materials, and values to describe quantities, e.g. `co2e_steel_ratio = Q(1.0, "unitless")`

**Pull request merged**
