### PR TITLE
Add Python 3.9 support

### PR DESCRIPTION
**Pull request by eumiro**
- [ ] Executed ``black -t py36 . && isort -rc . && flake8`` with no errors
- [x] The change is fully covered by automated unit tests
- [ ] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by hgrecco** [comment]
conda cannot resolve Python 3.9 and matplolib.

**Comment by eumiro** [comment]
https://travis-ci.org/github/hgrecco/pint/jobs/753297624

```
Setting environment variables from .travis.yml
$ export PKGS="python=3.9 numpy=1.17 matplotlib"
$ source ~/virtualenv/python3.6/bin/activate
$ python --version
Python 3.6.7
```

**Comment by jules-ch** [comment]
Thanks for the PR we moved CI to github actions & added Python 3.9 support.
I'm closing the PR since Python 3.9 testing should be covered.

**Pull request closed without merging**
