### PR TITLE
Unit with prefix defined for the first time while Context with redefinition is active

### LINKED ISSUE #1062: unit redefinition in a context breaks transform in another context
```python
ureg = pint.UnitRegistry()
for i in range(2):
    print(f"run {i}")
    ctx = pint.Context.from_lines(["@context _", "cal = 4 J"])
    with ureg.context("sp", ctx):
        u = ureg.Unit("nm")
        q = ureg.Quantity(1, u)
        q.to('J')
```
Output:
```
run 0
run 1
KeyError: 'nanometer'
```
The first run never fails.
The failure on the second run only happens if
1. ctx is recreated from lines between runs, and
2. the Unit instance is created while the contexts are enabled, and
3. the target unit is one used as a source in a redefinition in ctx (``q.to('ft')`` has no problem)

### PR DESCRIPTION
**Pull request by crusaderky**
Closes #1062

### CODE REVIEW

**Comment by crusaderky** [comment]
@hgrecco ready for review and merge.
Something's wrong with CI; travis is running (https://travis-ci.org/github/hgrecco/pint/builds/668335098) but it's not posting the status to the PR.

**Comment by crusaderky** [comment]
@hgrecco something wrong with bors too...

**Comment by keewis** [comment]
no, I think that's still [travis](https://travis-ci.org/github/hgrecco/pint/builds/). bors runs travis on the merge commit, and if travis does not report back bors times out...

**Comment by keewis** [comment]
@hgrecco: this one timed out, too. Retry?

**Pull request merged**
