### PR TITLE
Units fixes by KOLANICH

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by KOLANICH** [comment]
@hgrecco

**Comment by KOLANICH** [comment]
@hgrecco

**Comment by hgrecco** [comment]
This seem to break many tests. Maybe a parsing error?

**Comment by hgrecco** [comment]
I am closing this due to #666 . We can open a discussion about the "information" in another issue.

**Comment by covracer** [comment]
For anyone else trying to understand the history, https://github.com/hgrecco/pint/pull/1347 is the version of this that got merged.

**Pull request closed without merging**
