### PR TITLE
added automatic developer reference using sphinx - solve #827

### PR DESCRIPTION
**Pull request by larsschellhas**
This pull request adds a page "developers reference" to the documentation. It includes automatically generated information about all modules of the pint package.
Sphinx compiles the docstrings to well designed descriptions.

### CODE REVIEW

**Comment by larsschellhas** [comment]
This solves #827

**Comment by hgrecco** [comment]
Thanks a lot!

**Comment by larsschellhas** [comment]
You are welcome! Thanks for a great package!

**Comment by larsschellhas** [comment]
As soon as there are new docstrings they will be directly visible in the documentation! Looking forward to see it grow :)

**Pull request merged**
