### PR TITLE
Code Quality

### PR DESCRIPTION
**Pull request by labrys**
This fixes the following:

- Comparison to None
- Tests for membership
- Tests for object identity
- Bare except
- Old style classes
- Builtins being shadowed
- File encoding
- Deprecated function call
- Trailing comma on bare tuple

### CODE REVIEW

**Comment by hgrecco** [comment]
What is the relation of this and #661 ?

**Comment by labrys** [comment]
Doh it merged my two branches when I pushed them to my local fork after creating the PR.

**Comment by hgrecco** [comment]
Thanks for the PR. It looks good to me except for those two comments which I am not sure.

**Comment by labrys** [comment]
I've been busy the last couple of weeks.  I'll correct the PRs when I get a chance (hopefully Monday or Tuesday).  The very first commit 3af7a56 should have been the only commit in #661.  The rest were part of this PR.

**Comment by Silmathoron** [comment]
This PR looks pretty straightforward and useful, is there any reason for postponing the merge?

**Comment by crusaderky** [comment]
I have embedded all these changes into #931, please close

**Pull request closed without merging**
