### PR TITLE
add stochastic math implementation of random variable math

### PR DESCRIPTION
**Pull request by alexfeld**
Different method for implementing uncertain quantities

Also adds fix for #350 regarding functions of Quantities and Measurements not returning the correct objects.

### CODE REVIEW

**Comment by hgrecco** [comment]
I am finally able to put some time onto this again. The PR looks interesting indeed, but I think it deserves major discussion as it removes uncertainties and replace it for something completely different. In addition, I do think that we should create a sibling package for measurements.

**Comment by alexfeld** [comment]
Agreed. This is more of a suggestion to start the discussion.

**Comment by hgrecco** [comment]
My wish list:
1. a sibling package with everything that is Measurement related (let's call it PM for now)
2. PM should depend on Pint, but Pint should not depend on PM
3. Pint should be aware of PM and use if installed
4. PM should contain a list of definitions 
5. Pint should be able to integrate such definitions into the registry
6. PM should be able to do basic uncertainty propagation

More:
7. PM should be able to do propagate uncertainties with numpy functions without wrappers.
8. PM should be able to deal with covariance (like uncertainties)
9. PM should be able to propagate general functions (e.g. using the solution proposed here)

**Comment by hgrecco** [comment]
Please start this as a sibling package.

**Pull request closed without merging**
