### PR TITLE
Added mho sign (℧) for Siemens

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by hgrecco** [comment]
bors ping

**Comment by hgrecco** [comment]
I cannot merge this due to a problem with bors. Feel free to submit it again.

**Comment by KOLANICH** [comment]
@hgrecco, I have deleted the repo (but they could be pulled from your repo by commit hashes), could you merge my PRs manually without bors using only git or GitHub functionality?

**Comment by dopplershift** [comment]
Those commit hashes only existed in your repo, so if you deleted it, they're gone.

**Comment by xmo-odoo** [comment]
@dopplershift I don't think that's true, PR commits should be pulled into the target repository, and PR "branches" are available as `refs/pr/*`.

**Comment by dopplershift** [comment]
Ah, I didn't realize that still worked once the repo was deleted.

**Pull request closed without merging**
