### PR TITLE
Fix pint pandas notebook

### LINKED ISSUE #1317: pintpandas notebook doesn't display
I had broken the notebook https://pint.readthedocs.io/en/latest/pint-pandas.html with https://github.com/hgrecco/pint/pull/1254

### PR DESCRIPTION
**Pull request by andrewgsavage**
- [x] Closes #1317
- [x] Executed ``pre-commit run --all-files`` with no errors
- [x] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by andrewgsavage** [comment]
This can be merged now. I've commented the bits for plotting that I was trying to get working - will do that in another PR as that looks difficult.

**Comment by jules-ch** [comment]
I'll merge this.

Plotting seems to raise an error on dtype, you have dtype: object & matplotlib does not like it for plotting.

**Comment by jules-ch** [comment]
Thanks for the quick fix

**Comment by andrewgsavage** [comment]
> I'll merge this.
> 
> Plotting seems to raise an error on dtype, you have dtype: object & matplotlib does not like it for plotting.

How are you seeing this? I'm curious as I was struggling to debug this.
It's showing the dtypes as PintTypes - Is there a way to view outputs in the logs? I can only see this now it's merged.
```df_.dtypes
ShaftSpeed              pint[revolutions_per_minute]
FlowRate                     pint[meter ** 3 / hour]
DifferentialPressure                pint[kilopascal]
ShaftPower                            pint[kilowatt]
Efficiency                       pint[dimensionless]
dtype: object
```
I saw an error for not having numeric data to plot. This was an issue in earlier versions of pandas but is fixed now - this works on my pc with this version of pandas

My next steps were to replicate the modules installed in the docs environment .... ah that's why, it needs pandas 1.3! which should be out soon

**Pull request merged**
