### PR TITLE
Merge 0.12 tag

### PR DESCRIPTION
**Pull request by crusaderky**
Release 0.12 (https://github.com/hgrecco/pint/issues/1103) was done off an obsolete local master. Merge it back into master.

### CODE REVIEW

**Comment by crusaderky** [comment]
Note that I left version.py at ``0.12.dev0``, making it coherent with setuptools_scm (.dev versions are _after_ the numbered version)

**Comment by crusaderky** [comment]
@hgrecco ready for review and merge

**Comment by hgrecco** [comment]
Thanks for the fix.

**Comment by hgrecco** [comment]
I just released version 0.13 with your fix to the relase. Thanks a lot.

**Pull request merged**
