### PR TITLE
Add [+-]portion.inf to upcast_types

### LINKED ISSUE #1888: Quantity intervals
I'm trying to use `pint` with [portion](https://github.com/AlexandreDecan/portion) for quantity intervals. Portion defines its own singletons for positive and negative infinity that can compare to any type. However pint quantities can be compared only with other quantities:
```py
In [1]: import pint, portion

In [2]: portion.inf > pint.Quantity("3 mg")
Out[2]: True

In [3]: -portion.inf > pint.Quantity("3 mg")
Out[3]: False

In [4]: pint.Quantity("3 mg") < portion.inf
ValueError: Cannot compare PlainQuantity and <class 'portion.const._PInf'>

In [5]: pint.Quantity("3 mg") < -portion.inf
ValueError: Cannot compare PlainQuantity and <class 'portion.const._NInf'>
```

Now pint can parse `inf` as native float but this is not exactly equivalent to `portion.inf`, for example you can create a closed interval with infinite bounds:
```py
In [6]: portion.closed(pint.Quantity("-inf mg"), pint.Quantity("inf mg"))
Out[6]: [<Quantity(-inf, 'milligram')>,<Quantity(inf, 'milligram')>]
```

I think this can be fixed on the pint side by returning `NotImplemented` instead of raising `ValueError` for unhandled comparisons. 

cc @AlexandreDecan in case this can be somehow handled on the `portion` side.

### PR DESCRIPTION
**Pull request by gsakkis**
- [x] Closes #1888
- [x] Executed `pre-commit run --all-files` with no errors
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by AlexandreDecan** [comment]
Notice that the two paths (`portion.const._PInf` and `portion.const._NInf`) are part of the private API of `portion`. I don't know to which extent this private API will be subject to changes in the future. At the same time, I don't see any other good alternative :-)

**Comment by gsakkis** [comment]
@andrewgsavage could you take a look?

**Comment by andrewgsavage** [comment]
looks fine, just needs a maintainer to merge it.



> Notice that the two paths (`portion.const._PInf` and `portion.const._NInf`) are part of the private API of `portion`. I don't know to which extent this private API will be subject to changes in the future. At the same time, I don't see any other good alternative :-)

just needs a new PR with changes if you do end up changing it.

**Comment by andrewgsavage** [comment]
Why was this closed? Do you not want it merged?

**Pull request closed without merging**
