### PR TITLE
Add tests and documentation with improvement of downcast type compatibility (part of #845)

### LINKED ISSUE #37: Operating elementwise with numpy masked arrays
It is not working as suposed with masked arrays, it creats objects by elements.

https://gist.github.com/canesin/6072390

### LINKED ISSUE #845: Insuring interoperability of pint with other (non-unit) array-like types
When working with the new `__array_function__` implementation in #764, seeing what it takes to get pint `Quantity`'s working inside xarray (https://github.com/pydata/xarray/issues/525), and trying to wrap my head around [NEP 18](https://www.numpy.org/neps/nep-0018-array-function-protocol.html), I realized that (to the best of what I could find) pint's expected behavior with other ndarray-like types is not well-documented or tested for. And so, I hope that this issue could be a discussion on clarifying those expected behaviors and determining how to document and test them.

To start that discussion, I think it would make sense to split other array-like types into two categories, those that should wrap pint, and those that should be wrapped by pint, or in other words, determine where pint should fall in the "[type casting hierarchy](https://www.numpy.org/neps/nep-0013-ufunc-overrides.html#type-casting-hierarchy)". Based on https://github.com/pydata/xarray/issues/525#issuecomment-482651181 and other comments I've seen, a split like the following seems to be desired:

**Wrap pint Quantity**

- xarray DataArray

**Wrapped by pint Quantity**

- dask array
- cupy array
- sparse array
- numpy masked array (and of course ndarray)

(Pandas seems to have special handling through pint-pandas, and hopefully others that I'm missing can be added to either list as appropriate)

Does this make sense as a division, and should a list like this be documented anywhere?

Also, once #764 is in place, it seems like there will be a need for explicit identification of types in each category...types that should wrap pint are used in https://github.com/hgrecco/pint/blob/4dcbe78766269f985d1898601d8f5384a1511f2c/pint/quantity.py#L70, and types that should be wrapped by pint would be used with implementing the functionality mentioned in https://github.com/hgrecco/pint/pull/764/#issuecomment-523272038. However, what should be done about array-like types that are unknown to pint, and how can consistent behavior between different `Quantity`-related operations be assured?

Finally, should pint implement tests for all the types it expects to be able to wrap? I got the impression from https://github.com/pydata/xarray/issues/525 and https://github.com/pydata/xarray/pull/2956 that tests fit best with the type higher in the type casting hierarchy (the one doing the wrapping).

Please do correct me on anything I am mistaken about with the above rambling :smile:.

xref https://github.com/pydata/xarray/issues/525, https://github.com/pydata/xarray/pull/2956, https://github.com/hgrecco/pint/pull/764/, https://github.com/hgrecco/pint/issues/633, https://github.com/Unidata/MetPy/issues/996

EDIT: Discussion about arbitrarily nested metadata with NEP 18 implementers is ongoing at https://github.com/dask/dask/issues/5329, which will be good to keep in mind here too.

### PR DESCRIPTION
**Pull request by jthielen**
As a part of #845, this PR adds tests for downcast type compatibility with Sparse's `COO` and NumPy's `MaskedArray`, along with more careful handling of downcast types throughout the library. Also included is new documentation on array type compatibility, including the type casting hierarchy digraph by @shoyer and @crusaderky.

While this PR doesn't fully bring Pint's downcast type compatibility to a completed state, I think this gets it "good enough" for the upcoming release, and the remaining issues are fairly well defined:

- MaskedArray non-commutativity (https://github.com/hgrecco/pint/issues/633 / https://github.com/numpy/numpy/issues/15200)
- Dask compatibility (https://github.com/hgrecco/pint/issues/883)
- Addition of CuPy tests (no issue on issue tracker yet)

Because of that, I think this can close #845, but if @hgrecco you want that kept open until the above items are resolved, let me know.

- [x] Closes #37; Closes #845
- [x] Executed ``black -t py36 . && isort -rc . && flake8`` with no errors
- [x] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by hgrecco** [comment]
I agree with closing 845 and, if needed opening more specific issues referencing the upstream repos

**Comment by jthielen** [comment]
After testing this downstream with MetPy, the issue in https://github.com/hgrecco/pint/issues/37#issuecomment-21671778 reappeared, making it so that multiplying by a Unit on the right gives an object MaskedArray of Quantities instead of a Quantity with MaskedArray magnitude. This ends up being a pretty bad breaking change that makes the situation worse than before.

However, when I reverted the change to Unit replacing `__array_wrap__`/`__array_prepare__` with `__array_ufunc__`, the Sparse test now fails, since Sparse.COO times Unit requires the multiply ufunc to be implemented on Unit (since Sparse rightly defers).

So, unless I'm missing a fix that works for both Sparse and MaskedArray, there is a dilemma:

- Keep the change from this PR implementing `__array_ufunc__` on Unit, which is more future-proof and compatible with hierarchy-obeying types like Sparse.COO, but exacerbates https://github.com/numpy/numpy/issues/15200 and causes more issues with the commonly-used-but-problematic MaskedArray.
- Revert the change until https://github.com/numpy/numpy/issues/15200 is resolved, which keeps the MaskedArray multiplication issue the same as it was, but prevents proper behavior with types that require `__array_ufunc__` on Unit like Sparse.COO

Or, put another way, given that we can't have both, for which type of array would we rather have `array * ureg.m` work:

- Sparse.COO (and other ufunc-reliant types)?
- MaskedArray (as it was before)?

@hgrecco What are your thoughts on this?

**Comment by hgrecco** [comment]
This PR is good step into the right direction. `__array_ufunc__` (or similar) is a much better protocol than the previous one and something that `pint` was waiting for several years. My suggestion would be to keep this PR, document the problem and alert users what is the problem. Hopefully, this will be fixed in numpy soon.

**Pull request merged**
