### PR TITLE
add registry option for autoconvert_to_preferred

### LINKED ISSUE #1787: Document to_preferred
#1574 was merged without a documentation page. It would be good to have some examples in the docs. Opening this issue so it's not forgotten.

### PR DESCRIPTION
**Pull request by andrewgsavage**
- [x] Closes #1787 
- [x] Executed `pre-commit run --all-files` with no errors
- [x] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by andrewgsavage** [comment]
this is ready. any idea why some builds were cancelled?

**Comment by hgrecco** [comment]
I think is reay for merge, now right?

**Comment by andrewgsavage** [comment]
yup

**Comment by hgrecco** [comment]
I am trying to improve the quality of the git log, and for that purpose I have tried to a squash merge.

**Pull request merged**
