### PR TITLE
Matplotlib support

### LINKED ISSUE #317: plotting with pint quantities
I am interested in a combination between pint and matplotlib.
- The axes would recognize the unit and format the ticks appropriately, including automatically dynamically changing from e.g. meters to kilometers if the range of values is large. It would be analogous to the way datetimes are currently handled.
- The abv. unit would be formatted into the tick labels, or optionally would be added to the axis label (e.g. "height (m)")
- Error bars would automatically be generated based on uncertainty
- Probably more stuff I haven't thought of. Suggestions welcome.

I imagine this would take a lot of work with the matplotlib package, but I thought I'd ask here as there might be more interest here. Has this been proposed or attempted? Does anyone else think this would be really cool?

### PR DESCRIPTION
**Pull request by dopplershift**
This adds a method to `UnitRegistry` that hooks up handlers for `Quantity` instances within matplotlib's unit machinery:
```python
import pint
ureg = pint.UnitRegistry()
ureg.setup_matplotlib()
```
This support can also be disabled with:
```python
ureg.setup_matplotlib(False)
```

Closes #317.

### CODE REVIEW

**Comment by hgrecco** [comment]
Awesome!

One short thing. Can we add an image to the docs showing the output. I think it is worth doing it!

**Comment by dopplershift** [comment]
@hgrecco So I used matplotlib's sphinx extension to have it render the plots when you build the docs. I can add a static image if you prefer, but it seemed better to have the image generate "live" when building docs.

**Comment by hgrecco** [comment]
I think building it with the docs is a good idea as it help testing. But for this to work we will need to tell readthedocs that matplotlib, numpy and the sphinx extensions needs to be installed in order to build the docs. Can you create `requirements_docs.txt` file in the project root containing all the requirements? I will then configure readthedocs.

**Comment by dopplershift** [comment]
Done. I think I got what's needed.

**Pull request merged**
