### PR TITLE
Adding pint-convert script (see #1012)

### LINKED ISSUE #1012: Command-line unit converter
I wrote, mainly for my own use, a little script to use pint for quickly doing conversion between units and checking dimensionalities or conversion factors. It supports uncertainties in the physical constants (not in the values to be converted). Some examples:

```
$ unit_convert.py Eh   # to SI
1 hartree = 4.359744722207(8)e-18 kg·m²/s²

$ unit_convert.py Eh kcal/mol  # to other units, even using some default contexts
1 hartree = 627.509474063(1) kcal/mol
$ unit_convert.py Eh Btu
1 hartree = 4.132240110674(8)e-21 Btu
$ unit_convert.py Eh cm_1
1 hartree = 219474.631363 cm_1

$ unit_convert.py -p6 25torr psi  # request precision
25 torr = 0.483419 psi

$ unit_convert.py "(3.47Eh/(0.12Å)*pi)" N  # more complex expressions
28.916666666666668 hartree * pi / angstrom = 3.960583392343(8)e-06 N
```

This is of course all done by pint, and the script does little more than setting the uncertainties, print formats and some defaults, and in that sense I guess it just reflects some personal preferences/needs.

Would it be appropriate to include the script with pint somehow? Would it be useful for others? Should I host it elsewhere? Is there some other place where it may fit better?

This is the script:
```
#!/usr/bin/env python3

import argparse
from pint import UnitRegistry
import sys
import re

parser = argparse.ArgumentParser(description='Unit converter.')
parser.add_argument('-s', '--system', metavar='sys', default='SI', help='unit system to convert to (default: SI)')
parser.add_argument('-p', '--prec', metavar='n', type=int, default=12, help='number of maximum significant figures (default: 12)')
parser.add_argument('-u', '--prec-unc', metavar='n', type=int, default=2, help='number of maximum uncertainty digits (default: 2)')
parser.add_argument('-U', '--no-unc', dest='unc', action='store_false', help='ignore uncertainties in constants')
parser.add_argument('-C', '--no-corr', dest='corr', action='store_false', help='ignore correlations between constants')
parser.add_argument('fr', metavar='from', type=str, help='unit or quantity to convert from')
parser.add_argument('to', type=str, nargs='?', help='unit to convert to')
args = parser.parse_args()

ureg = UnitRegistry()
ureg.auto_reduce_dimensions = True
ureg.autoconvert_offset_to_baseunit = True
ureg.enable_contexts('Gau', 'ESU', 'sp', 'energy', 'boltzmann')
ureg.default_system = args.system

if args.unc:
  import uncertainties
  import numpy as np
  # Measured constans subject to correlation
  #  R_i: Rydberg constant
  #  g_e: Electron g factor
  #  m_u: Atomic mass constant
  #  m_e: Electron mass
  #  m_p: Proton mass
  #  m_n: Neutron mass
  R_i = (ureg._units['R_inf'].converter.scale, 0.0000000000021e7)
  g_e = (ureg._units['g_e'].converter.scale,   0.00000000000035)
  m_u = (ureg._units['m_u'].converter.scale,   0.00000000050e-27)
  m_e = (ureg._units['m_e'].converter.scale,   0.00000000028e-30)
  m_p = (ureg._units['m_p'].converter.scale,   0.00000000051e-27)
  m_n = (ureg._units['m_n'].converter.scale,   0.00000000095e-27)
  if args.corr:
    # Correlation matrix between measured constants (to be completed below)
    #                   R_i       g_e       m_u       m_e       m_p       m_n
    corr = np.array([[  0.0    , -0.00206,  0.00369,  0.00436,  0.00194,  0.00233],   # R_i
                     [  0.0    ,  0.0    ,  0.99029,  0.99490,  0.97560,  0.52445],   # g_e
                     [  0.0    ,  0.0    ,  0.0    ,  0.99536,  0.98516,  0.52959],   # m_u
                     [  0.0    ,  0.0    ,  0.0    ,  0.0    ,  0.98058,  0.52714],   # m_e
                     [  0.0    ,  0.0    ,  0.0    ,  0.0    ,  0.0    ,  0.51521],   # m_p
                     [  0.0    ,  0.0    ,  0.0    ,  0.0    ,  0.0    ,  0.0    ]])  # m_n
    corr += corr.T
    np.fill_diagonal(corr, 1.0)
    (R_i, g_e, m_u, m_e, m_p, m_n) = uncertainties.correlated_values_norm([R_i, g_e, m_u, m_e, m_p, m_n], corr)
  else:
    R_i = uncertainties.ufloat(*R_i)
    g_e = uncertainties.ufloat(*g_e)
    m_u = uncertainties.ufloat(*m_u)
    m_e = uncertainties.ufloat(*m_e)
    m_p = uncertainties.ufloat(*m_p)
    m_n = uncertainties.ufloat(*m_n)
  ureg._units['R_inf'].converter.scale = R_i
  ureg._units['g_e'].converter.scale   = g_e
  ureg._units['m_u'].converter.scale   = m_u
  ureg._units['m_e'].converter.scale   = m_e
  ureg._units['m_p'].converter.scale   = m_p
  ureg._units['m_n'].converter.scale   = m_n

  # Measured constants with zero correlation
  ureg._units['gravitational_constant'].converter.scale = uncertainties.ufloat(ureg._units['gravitational_constant'].converter.scale, 0.00015e-11)
  ureg._units['d_220'].converter.scale                  = uncertainties.ufloat(ureg._units['d_220'].converter.scale,                  0.000000032e-10)
  ureg._units['K_alpha_Cu_d_220'].converter.scale       = uncertainties.ufloat(ureg._units['K_alpha_Cu_d_220'].converter.scale,       0.00000022)
  ureg._units['K_alpha_Mo_d_220'].converter.scale       = uncertainties.ufloat(ureg._units['K_alpha_Mo_d_220'].converter.scale,       0.00000019)
  ureg._units['K_alpha_W_d_220'].converter.scale        = uncertainties.ufloat(ureg._units['K_alpha_W_d_220'].converter.scale,        0.000000098)

  ureg._root_units_cache = dict()
  ureg._build_cache()

def convert(u_from, u_to=None, unc=None, factor=None):
  q = ureg.Quantity(u_from)
  fmt = '.{}g'.format(args.prec)
  if unc:
    q = q.plus_minus(unc)
  if u_to:
    nq = q.to(u_to)
  else:
    nq = q.to_base_units()
  if (factor):
    q *= ureg.Quantity(factor)
    nq *= ureg.Quantity(factor).to_base_units()
  prec_unc = use_unc(nq.magnitude, fmt, args.prec_unc)
  if (prec_unc > 0):
    fmt = '.{}uS'.format(prec_unc)
  else:
    try:
      nq = nq.magnitude.n * nq.units
    except:
      pass
  fmt = '{:' + fmt + '} {:~P}'
  print(('{:} = ' + fmt).format(q, nq.magnitude, nq.units))

def use_unc(num, fmt, prec_unc):
  unc = 0
  try:
    if (isinstance(num, uncertainties.UFloat)):
      full = ('{:'+fmt+'}').format(num)
      unc = re.search(r'\+\/-[0.]*([\d.]*)', full).group(1)
      unc = len(unc.replace('.', ''))
  except:
    pass
  return max(0, min(prec_unc, unc))

convert(args.fr, args.to)
```

### PR DESCRIPTION
**Pull request by Jellby**
A script for quick command-line conversion is provided. It supports uncertainties and correlations in physical constants, but these are hard-coded in the script, because they are not defined by `pint` (yet).

- [x] Closes #1012.
- [x] Executed ``black -t py36 . && isort -rc . && flake8`` with no errors
- [ ] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by hgrecco** [comment]
In general, I would agree to merge it for 0.11. A few things
1. Run `black -t py36 . && isort -rc . && flake8` to make the tests pasts
2. Change `pint_convert` to `pint-convert` in the docstring

**Comment by hgrecco** [comment]
Looks good to me. I will merge it next week to let people comment.

I was also thinking where shall we document this. I think a few lines on the readme would be nice, just above GUI website. But also in the docs.

**Comment by Jellby** [comment]
Added some documentation. How does this look?

**Pull request merged**
