### PR TITLE
The grand Python 2.7 cleanup

### PR DESCRIPTION
**Pull request by crusaderky**
xref #906, #908 

Remove all Python 2.7 syntax from the codebase

### CODE REVIEW

**Comment by crusaderky** [comment]
@hgrecco ready for review and merge

**Comment by hgrecco** [comment]
Please fix the conflict and update the README  and README.rst to make clear is only for Python 3.6+ Additionally, it would be nice if you add a phrase saying "If you need Python 2.7 or 3.4/3.5 compatibility use Pint 0.9"

**Comment by crusaderky** [comment]
@hgrecco done as requested

**Pull request merged**
