### PR TITLE
Pin pandas version

### PR DESCRIPTION
**Pull request by znicholls**

### CODE REVIEW

**Comment by znicholls** [comment]
@hgrecco I think this is right but the tests aren't running on the commit which renables pandas tests so I can't be sure...

**Comment by hgrecco** [comment]
bors try

**Comment by hgrecco** [comment]
bors ping

**Comment by hgrecco** [comment]
According to travis, this PR passed https://travis-ci.org/hgrecco/pint/builds/447439213

bors r+

**Comment by znicholls** [comment]
sorry @hgrecco got my spacing wrong in the travis file... the requests are shown here for future reference https://travis-ci.org/hgrecco/pint/requests

**Pull request merged**
