### PR TITLE
WIP: add pandas interface

### PR DESCRIPTION
**Pull request by znicholls**
Initial attempts at a solution for #645 which, if it works, would also provide a use of ExtensionArray with pandas and hence make progress on https://github.com/pandas-dev/pandas/issues/10349...

Like @wisp3rwind I am both a numpy and pandas newbie so don't really know what I'm doing. 

I've got it to the stage where pandas isn't automatically converting my data to a numpy array but there's still a lot to be desired. See the following (the `Makefile` should give at least some indication of how my environment is set up... I think all you need is Python3.6, pandas>=0.23.0)

```python
In [1]: from pint.pandas_interface import PintArray

In [2]: import pandas as pd

In [3]: df = pd.DataFrame({"address": PintArray([1, 2, 3])})

# a start
In [4]: df
Out[4]: 
          address
0 1 dimensionless
1 2 dimensionless
2 3 dimensionless

In [5]: df.dtypes
Out[5]: 
address    <class 'pint.pandas_interface.PintType'>
dtype: object

In [6]: df['address']
Out[6]: 
0   1 dimensionless
1   2 dimensionless
2   3 dimensionless
Name: address, dtype: pintarray

In [7]: df['address'].values.data
Out[7]: array([1, 2, 3]) <Unit('dimensionless')>

In [8]: df['address'].values
Out[8]: <pint.pandas_interface.PintArray at 0x10d99bd30>

In [9]: import pint

In [10]: ureg = pint.UnitRegistry()

In [11]: heights = [150, 160, 165] * ureg.meter

In [12]: df = pd.DataFrame({"address": PintArray([1, 2, 3]), "height": PintArray(heights
    ...: )})

# looks ok
In [13]: df
Out[13]: 
          address    height
0 1 dimensionless 150 meter
1 2 dimensionless 160 meter
2 3 dimensionless 165 meter

In [14]: df['height']
Out[14]: 
0   150 meter
1   160 meter
2   165 meter
Name: height, dtype: pintarray

In [15]: df['height'].data
/Users/zebedeenicholls/miniconda3/bin/ipython:1: FutureWarning: Series.data is deprecated and will be removed in a future version
  #!/Users/zebedeenicholls/miniconda3/bin/python
Out[15]: array([150, 160, 165]) <Unit('meter')>

# not ideal
In [16]: df['height'].values
Out[16]: <pint.pandas_interface.PintArray at 0x11784ab00>

In [17]: df['height'].values.data
Out[17]: array([150, 160, 165]) <Unit('meter')>

# not ideal
In [18]: df['height'] + 3 * ureg.cm
---------------------------------------------------------------------------
DimensionalityError                       Traceback (most recent call last)
<ipython-input-18-49b18c1d8d0f> in <module>()
----> 1 df['height'] + 3 * ureg.cm

~/miniconda3/lib/python3.6/site-packages/pandas/core/ops.py in wrapper(left, right)
   1067             rvalues = rvalues.values
   1068 
-> 1069         result = safe_na_op(lvalues, rvalues)
   1070         return construct_result(left, result,
   1071                                 index=left.index, name=res_name, dtype=None)

~/miniconda3/lib/python3.6/site-packages/pandas/core/ops.py in safe_na_op(lvalues, rvalues)
   1031         try:
   1032             with np.errstate(all='ignore'):
-> 1033                 return na_op(lvalues, rvalues)
   1034         except Exception:
   1035             if is_object_dtype(lvalues):

~/miniconda3/lib/python3.6/site-packages/pandas/core/ops.py in na_op(x, y)
   1010 
   1011         try:
-> 1012             result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
   1013         except TypeError:
   1014             if isinstance(y, (np.ndarray, ABCSeries, pd.Index)):

~/miniconda3/lib/python3.6/site-packages/pandas/core/computation/expressions.py in evaluate(op, op_str, a, b, use_numexpr, **eval_kwargs)
    203     use_numexpr = use_numexpr and _bool_arith_check(op_str, a, b)
    204     if use_numexpr:
--> 205         return _evaluate(op, op_str, a, b, **eval_kwargs)
    206     return _evaluate_standard(op, op_str, a, b)
    207 

~/miniconda3/lib/python3.6/site-packages/pandas/core/computation/expressions.py in _evaluate_standard(op, op_str, a, b, **eval_kwargs)
     63         _store_test_result(False)
     64     with np.errstate(all='ignore'):
---> 65         return op(a, b)
     66 
     67 

~/Documents/AGCEC/Misc/pint/pint/quantity.py in __add__(self, other)
    724             return self.to_timedelta() + other
    725         else:
--> 726             return self._add_sub(other, operator.add)
    727 
    728     __radd__ = __add__

~/Documents/AGCEC/Misc/pint/pint/quantity.py in _add_sub(self, other, op)
    635                                _to_magnitude(other, self.force_ndarray))
    636             else:
--> 637                 raise DimensionalityError(self._units, 'dimensionless')
    638             return self.__class__(magnitude, units)
    639 

DimensionalityError: Cannot convert from 'centimeter' to 'dimensionless'

# not ideal
In [19]: df['height'].values.data + 3 * ureg.cm
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-28f7dceba636> in <module>()
----> 1 df['height'].values.data + 3 * ureg.cm

~/Documents/AGCEC/Misc/pint/pint/quantity.py in __add__(self, other)
    724             return self.to_timedelta() + other
    725         else:
--> 726             return self._add_sub(other, operator.add)
    727 
    728     __radd__ = __add__

~/Documents/AGCEC/Misc/pint/pint/quantity.py in _add_sub(self, other, op)
    619         :type op: function
    620         """
--> 621         if not self._check(other):
    622             # other not from same Registry or not a Quantity
    623             if _eq(other, 0, True):

~/Documents/AGCEC/Misc/pint/pint/util.py in _check(self, other)
    622             mess = 'Cannot operate with {} and {} of different registries.'
    623             raise ValueError(mess.format(self.__class__.__name__,
--> 624                                          other.__class__.__name__))
    625         else:
    626             return False

ValueError: Cannot operate with Quantity and Quantity of different registries.
```

It would be awesome to get some eyes on this that know what they're doing much better than I do. I can run all the pint tests and they seem to pass ok but I am failing heaps of the pandas tests and I really can't work out why.

### CODE REVIEW

**Comment by andrewgsavage** [comment]
I've got a WIP version that I think is a bit further than this . I'll try to work out how to fork this and move it from a jupyter notebook now.  (am a noob at git)

Skimming through your code:
I haven't worked out how to get  access to the quantity class properly either 

re PintType
Analagous to IPv4v6Base.register(ipaddress.IPv4Address)
https://github.com/ContinuumIO/cyberpandas/blob/master/cyberpandas/ip_array.py
The metaclass for PintType should register Quantity, as this is what is expected to be returned when doing a ExtensionArray[item] 

    @property
    def type(self):
        # type: () -> type
        """The scalar type for the array, e.g. ``int``
        It's expected ``ExtensionArray[item]`` returns an instance
        of ``ExtensionDtype.type`` for scalar ``item``.
        """
        raise AbstractMethodError(self)
https://github.com/pandas-dev/pandas/blob/master/pandas/core/dtypes/base.py

This makes me believe pandas is expecting an array of scalar items, so for quantities that'd be 
[<Quantity(1, 'meter')>,
 <Quantity(2, 'meter')>,
 <Quantity(2, 'meter')>,
 <Quantity(3, 'meter')>]
(this is also how I've got _construct_from_sequence to work)
Which leaves several immediately obvious ways to create an Extensionarray, 
sequence of scalar quantities
vector quantity
matrix quantity (not allowed as Extensionarray are only 1d)
scalar quantity (acceptable? I haven't been dealing with this yet)

re construct_from_string comment
I think this is used to allow pandas to interpret a column as a pinttype when doing pd.read_csv(... dtype={"a":"pint"}. Can't find what I read to make me think this though!
I think there's the potential to to have an extensiontype for every unit, which will allow pandas to read a column with dtype={"columnname":"meter" and create an extensionarray directly.

re numpy
I don't think it's an issue having a numpy dependency as pandas needs it.

**Comment by znicholls** [comment]
> I've got a WIP version that I think is a bit further than this

Wicked! Any help is massively appreciated!

> 'll try to work out how to fork this and move it from a jupyter notebook now

If you want a hand let me know, I think I've made most mistakes with git so hopefully can point you in the right direction.

> The metaclass for PintType should register Quantity

ok, showing my noobness here, I don't know what registering is...

> I think there's the potential to to have an extensiontype for every unit, which will allow pandas to read a column with dtype={"columnname":"meter" and create an extensionarray directly.

that sounds cool and very useful

**Comment by andrewgsavage** [comment]
Sorry, do whatevers easiest / most proper! (Not familiar with how best to use GitHub)

See the cyber link, that uses registration around where iptype is defined

**Comment by znicholls** [comment]
> Sorry, do whatevers easiest / most proper! (Not familiar with how best to use GitHub)

No need to apologise, it's all a learning process. I'll make a pull request into your fork to add the tests/bits and pieces I've learnt. I'll close this PR in favour of yours, #672

**Comment by znicholls** [comment]
> warning heard, is the cyberpandas setup a good one to follow? Or should we dive deeper into the pandas interface to work out where all the joins need to be made?

ignore this, found this https://github.com/pandas-dev/pandas/blob/master/pandas/core/arrays/integer.py and now understand what you mean

**Pull request closed without merging**
