### PR TITLE
implement quantile

### PR DESCRIPTION
**Pull request by keewis**
This implements `numpy.quantile` and `numpy.nanquantile`.

- [x] Executed ``black -t py36 . && isort -rc . && flake8`` with no errors
- [x] The change is fully covered by automated unit tests
- [ ] Documented in docs/ as appropriate
- [ ] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by keewis** [comment]
Is there a reason the output in `numpy.ipynb` was not stripped? If the notebook does not need any manual interaction, `nbsphinx` should be able to execute it but it won't if the notebook is "pre-executed" (if I didn't misunderstand anything).

The `getattr` guard is necessary because `numpy=1.14` does not provide `quantile` / `nanquantile`.

**Comment by jthielen** [comment]
@keewis The only reason for the output not being stripped was that when I had tested it out, the sphinx build only rendered what was in the notebook rather than doing any execution. But, perhaps I had something configured incorrectly, so feel free to update that if you can get it working!

**Comment by keewis** [comment]
turns out I added the `getattr` guard to the wrong function. Should I undo that?

notebook: It does work once you cleared every output (although the graphviz output looked cropped). Since there are quite a few new dependencies in `numpy.ipynb`, we would need to expand `requirements_docs.txt` a lot. That seems a bit out of scope for this PR, though.

**Comment by keewis** [comment]
this is ready for review and merge.

The docs update for this PR should be automatic (it is not right now, but that is for a new PR to fix), so nothing to do here.

**Pull request merged**
