### PR TITLE
Prevent crash when context is None

### PR DESCRIPTION
**Pull request by eric-wieser**
Triggered by `linalg`, among other things

### CODE REVIEW

**Comment by eric-wieser** [comment]
There also seems to be a problem with `__array_wrap__`  and `np.maximum`

**Comment by eric-wieser** [comment]
Coverage has "decreased" only for numpy-less builds - not really a surprise or a failure

**Comment by hgrecco** [comment]
:+1:

**Comment by eric-wieser** [comment]
Ok, I've combined this with #421

**Comment by eric-wieser** [comment]
@hgrecco, what's the upgrade path from a 👍 to a merge? ;)

**Comment by hgrecco** [comment]
I think this is no longer needed after #905. I am closing, please reopen if needed.

**Pull request closed without merging**
