### PR TITLE
Improved the API documentation to avoid breaking intersphinx

### LINKED ISSUE #1637: Intersphinx issue
With the release of 0.20, `pint.Quantity` and `pint.Unit` no longer appear in the intersphinx catalog (`objects.inv`) and can't be linked in other sphinx docs any more. I get errors like:
```
 WARNING: py:obj reference target not found: pint.Quantity
```

### PR DESCRIPTION
**Pull request by hgrecco**
- [ ] Closes #1637
- [ ] Executed ``pre-commit run --all-files`` with no errors
- [ ] The change is fully covered by automated unit tests
- [ ] Documented in docs/ as appropriate
- [ ] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by marscher** [comment]
Thanks a lot for this quick fix. Just tested with latest on RTD. Now I receive the following:
```
docstring of pint.quantity.Quantity:1: WA: pint.facets.plain.quantity.Magnitude
```

**Comment by hgrecco** [comment]
Have you try referencing  `pint.Quantity`?

**Comment by marscher** [comment]
Sorry, the error popped up, since I did some evil hacks on `__module__`! 
Now it works like a charm!

**Comment by hgrecco** [comment]
Just released 0.20.1 fixing this.
Thanks for reporting

**Comment by jules-ch** [comment]
Thanks @hgrecco for tackling this

**Comment by hgrecco** [comment]
Just to leave a note for the future, sphinx does not work well with dynamically generated classes. `pint.Quantity`, `pint.Unit`, `pint.Measurement`, and others are dynamically generated classes based on the `UnitRegistry` parents. Maybe instead of doing that, we can create them manually and check that the parents are properly organized.

Additionally, sphinx is not very happy with classes defined in other places. That is why I have uses autoclass instead of automodules.

**Comment by jules-ch** [comment]
Something weird happened with latest change, Grid links now link to scipy and dask for the getting started & API Reference

**Comment by hgrecco** [comment]
intersphinx being too clever masquerades an error.

**Comment by jules-ch** [comment]
Made a PR for this

**Pull request merged**
