### PR TITLE
Adding compatability code for changes in importlib.resources. Closes #1618

### LINKED ISSUE #1618: importlib.resource.path (pint/parser.py:264) is deprecated in Python 3.11, use files() instead
```
../lib/python3.11/site-packages/pint/parser.py:264: DeprecationWarning: path is deprecated. 
Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
```

### PR DESCRIPTION
**Pull request by hwalinga**
- [x] Closes #1618
- [x] Executed ``pre-commit run --all-files`` with no errors
- [x] The change is fully covered by automated unit tests (I guess you will add 3.11 to tox setup.)
- [ ] Documented in docs/ as appropriate (not needed)
- [ ] Added an entry to the CHANGES file (just too minor)

### CODE REVIEW

**Comment by hwalinga** [comment]
Alternatively you can use https://pypi.org/project/importlib-resources/, but that would add a new dependency to the project and there isn't that much use of it.

**Comment by hgrecco** [comment]
Thanks for submitting this patch. I will merge the same concept into the new parser.

**Comment by hgrecco** [comment]
Merged this concept into https://github.com/hgrecco/flexparser

Now flexparser is ready for Python 3.11 (and therefore pint will be able to parse resources without warnings)
https://github.com/hgrecco/flexparser/actions/runs/3301572697

As soon as Python 3.11 is released, I will release a new version of flexparser against it and incorporate the new version to `pint/_vendor`

Thanks!

**Comment by hwalinga** [comment]
>As soon as Python 3.11 is released,

Just so you know, that is this Monday  ; )

Thanks for the fix!

**Comment by hgrecco** [comment]
Thank you. I just pushed that we test the whole code base against 3.11-dev in #1622

**Comment by hgrecco** [comment]
All tests are passing on python 3.11 but I still need to check the logs.

I think we should update the current tests to fail on DeprecationWarning and PendingDeprecationWarning. Anyone knows a global way to do it in pytests?

**Comment by hgrecco** [comment]
and maybe even fail on all warnings (except those that are explicitly caught).

**Pull request closed without merging**
