### PR TITLE
add `pint-xarray`'s CI to the downstream status page

### PR DESCRIPTION
**Pull request by keewis**
- [x] Executed `pre-commit run --all-files` with no errors

### CODE REVIEW

**Comment by keewis** [comment]
I wondered if we could improve the page by formatting the list as a table, and the result is the last commit here. This does make the page look a bit nicer, although `mdformat` expands the source to be equally sized everywhere, including the huge urls, which makes editing a bit hard (does anyone know if we can avoid that somehow?).

**Comment by hgrecco** [comment]
@keewis I agree that the rendered table looks much nicer! I do not know if there is a way to improve the non rendered format. Is there a way to use indirection?

**Comment by keewis** [comment]
there is in [github flavored markdown](https://github.github.com/gfm/#images), not sure about others. I guess it depends on what we want to do with that page?

**Comment by hgrecco** [comment]
IMO is only for github. We use it to check if everything is ok before releasing!

**Pull request merged**
