### PR TITLE
expose some of the internal test functions in `pint.testing`

### LINKED ISSUE #1272: np.testing.assert_equal does not work with quantity lists
When creating a list of quantities from a numpy array, numpy's built-in test methods for array comparison no longer work. This is breaking a lot of my test suite now that I am trying to incorporate pint's unit capabilities into my packages. Is there an easy way around this, or am I just going to have to write a wrapper function and swap it out for numpy's?

```
import pint
import numpy as np


ureg = pint.UnitRegistry()
data = ureg.mV * np.array([1, 2, 3])
np.testing.assert_equal(data, data) # This fails

```

### LINKED ISSUE #1285: Where is pint.testing API reference?
I cannot find the pint.testsuite API reference. It was referenced in issue #1272, but it doesn't appear on the main API page. I'd like to test that two pint quantities are equal, and right now I'm doing it with my own function.

### PR DESCRIPTION
**Pull request by keewis**
just as a side note, it might be good to change the `autodoc`-based documentation to something else, like `autosummary`

- [x] Closes #1285, closes #1272
- [x] Executed ``pre-commit run --all-files`` with no errors
- [ ] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by keewis** [comment]
okay, I cheated my way around a bug in `is_compatible_with` when it is used with contexts (it ignores already active contexts), but I don't know enough about contexts to fix that in a general way. Do you have any ideas, @hgrecco, @jules-ch?

**Comment by jules-ch** [comment]
Hi @keewis do you have a minimal example for your issue with `is_compatible_with` ?

**Comment by keewis** [comment]
it would be something like this (taken from `test_contexts.py::TestDefinedContexts::test_spectroscopy`)
```python
In [6]: ureg = pint.UnitRegistry()
   ...: 
   ...: a = 532.0 * ureg.nm
   ...: b = 563.5 * ureg.terahertz
   ...: 
   ...: with ureg.context("sp"):
   ...:     print(a.to(ureg.terahertz))
   ...:     assert a.is_compatible_with(b), "not compatible"
   ...: 
563.5196578947367 terahertz
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-6-8eaa63cfa960> in <module>
      6 with ureg.context("sp"):
      7     print(a.to(ureg.terahertz))
----> 8     assert a.is_compatible_with(b), "not compatible"
      9 

AssertionError: not compatible
```
`ureg.is_compatible_with` behaves the same way (so at least it's consistent)

**Comment by jules-ch** [comment]
Can you file an issue regarding this, I'll quickly fix that.

**Comment by keewis** [comment]
sure

**Comment by jules-ch** [comment]
Gonna merge this after CI completes

**Pull request merged**
