### PR TITLE
Expose matplotlib formatter

### LINKED ISSUE #1702: Controlling the format of axis label with matplotlib
It'd be nice if users were able to control the format of the units in the axis.

For instance, instead of `bequerel/hour` one may want `Bq/h`.

I believe the format here would need to be exposed.
https://github.com/hgrecco/pint/blob/521dc80fabdacae20d57d9e3dce95e04633894ca/pint/matplotlib.py#L19-L24

What do people think?

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
This PR adds the possibility to change the matplotlib unit format.

Usage:

```python
import pint

ureg = pint.UnitRegistry()

ureg.setup_matplotlib()
ureg.mpl_formatter = "{:~P}"
#  ureg.mpl_formatter = "{:P}"  # default
#  ureg.mpl_formatter = "${:~L}$"

t = [1, 2, 3] * ureg.Bq**2

import matplotlib.pyplot as plt

plt.plot(t)
plt.show()
```

- [x] Closes #1702
- [x] Executed ``pre-commit run --all-files`` with no errors
- [x] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
@hgrecco any chance we could have a look at this?

**Comment by RemDelaporteMathurin** [comment]
@jules-ch Hi, any chance I could get a review on this? If the fix isn't suitable then I'm happy to close this :-)

**Comment by hgrecco** [comment]
I will be reviewing everything in the upcoming days, hopefully I will be releasing a new version next week.

**Comment by hgrecco** [comment]
Great PR, thanks.

**Pull request merged**
