### PR TITLE
copy.deepcopy(UnitRegistry())

### LINKED ISSUE #856: deepcopy(ureg) broken
As of pint 0.9:
```python
import pint
import copy
ureg = pint.UnitRegistry()
copy.deepcopy(ureg)
```
Output:
```
lib/python3.7/copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

lib/python3.7/site-packages/pint/util.py in __hash__(self)
    475 
    476     def __hash__(self):
--> 477         if self.scale != 1.0:
    478             mess = 'Only scale 1.0 ParserHelper instance should be considered hashable'
    479             raise ValueError(mess)

AttributeError: scale
```
```python
>>> c = pint.util.ParserHelper(scale=1)
>>> c2 = copy.deepcopy(c)
>>> c2.scale
AttributeError: scale
```

### PR DESCRIPTION
**Pull request by crusaderky**
Closes #856 

Allow creating an independent copy of a UnitRegistry through deepcopy().
Also introduce several speedups in UnitsContainer and ParserHelper.

### CODE REVIEW

**Comment by crusaderky** [comment]
copy.deepcopy misbehaves in case of dynamic class definition, such as that performed by ``build_unit_class``:

```python
>>> def gen_C():
...     class C:
...         pass
...     return C

>>> C1 = gen_C()
>>> C2 = copy.deepcopy(C1)
>>> C2 is C1
True
```

**Comment by crusaderky** [comment]
...aaand done :)

This gives _some_ performance benefit compared to re-initialising everything from the beginning:
```python
%timeit pint.UnitRegistry()
135 ms ± 2.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
ureg = pint.UnitRegistry()
%timeit copy.deepcopy(ureg)
42.7 ms ± 799 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by crusaderky** [comment]
@hgrecco this is ready for review and merge

**Comment by hgrecco** [comment]
Great. I would like a second opinion as this is a rather large change. Maybe @andrewgsavage or @jondoesntgit can take also a look.

**Comment by crusaderky** [comment]
@hgrecco @andrewgsavage  @jondoesntgit ping - any observations before this can be merged?

**Comment by jondoesntgit** [comment]
I don't have any observations. This is a bug that I've never had to worry about in my code.

**Comment by andrewgsavage** [comment]
Me neither

**Comment by crusaderky** [comment]
Thank you!

**Pull request merged**
