### PR TITLE
broadcast_arrays

### PR DESCRIPTION
**Pull request by andrewgsavage**
- [x] Closes #1607  (insert issue number)
- [x] Executed ``pre-commit run --all-files`` with no errors
- [x] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

### CODE REVIEW

**Comment by hgrecco** [comment]
This seems to be ready, right?

**Comment by andrewgsavage** [comment]
yes

**Comment by hgrecco** [comment]
excelent!

**Pull request merged**
